- aws-lc-rs/Cargo.toml
> Add description in aws-lc-rs/Cargo.toml

- README.md
- aws-lc-rs/Cargo.toml
- aws-lc-rs/README.md
- aws-lc-rs/README.tpl
> Update manifest for 1.0.0

- .github/workflows/ci.yml
N/A
* Use GitHub's dependency-review-action instead of our current "license" and "audit" jobs.
N/A
N/A
> Use GitHub dependency-review-action

- scripts/generate/_collect_symbols_build.sh
> Update collect symbols script for latest aws-lc changes

- README.md
- aws-lc-rs/README.md
- aws-lc-rs/src/lib.rs
N/A
Add more documentation relating to our build requirements.
N/A
`cargo readme > README.md`
> Better documentation on the build

- scripts/generate/_generate_all_bindings_flavors.sh
- scripts/generate/_run_supported_symbol_builds.sh
- scripts/generate/_test_supported_builds.sh
N/A
Our crate generation scripts launch docker comtainers in the background and use `wait` to wait for them to finish. When used w/o parameters, `wait` will succeed even when the processes it's waiting on have failed.
N/A
I regenerated the aws-lc-fips-sys crate successfully.
> Wait for specific pid

- .github/workflows/ci.yml
- aws-lc-fips-sys/builder/bindgen.rs
- aws-lc-fips-sys/builder/main.rs
N/A
* Resolve come clippy complaints in our fips crate build scripts.
* The "bindgen" feature is enabled for clippy tests in our CI.
N/A
> Fix clippy for fips build

- aws-lc-rs/Cargo.toml
- aws-lc-rs/README.md
- aws-lc-rs/src/lib.rs
N/A
* Updated version to 1.0.2
* Updated documentation to indicate our support for Windows.
N/A
N/A
> Update documentation and version to 1.0.2

- aws-lc-rs/src/aead.rs
- aws-lc-rs/src/aead/chacha20_poly1305_openssh.rs
- aws-lc-rs/src/aead/nonce.rs
- aws-lc-rs/src/aead/nonce_sequence/counter32.rs
- aws-lc-rs/src/aead/nonce_sequence/counter64.rs
- aws-lc-rs/src/lib.rs
- aws-lc-rs/src/nonce.rs
> Refactor Nonce to nonce::FixedLength

- aws-lc-rs/src/cipher.rs
> Implement Debug trait for Cipher types

- .github/PULL_REQUEST_TEMPLATE.md
Remove two trailing new lines
No code harmed.
> Remove trailing newline in pr template

- aws-lc-rs/benches/cipher_benchmark.rs
- aws-lc-rs/examples/cipher.rs
- aws-lc-rs/src/cipher.rs
- aws-lc-rs/src/iv.rs
- aws-lc-rs/tests/cipher_test.rs
N/A
Keep distinct EncryptionContext and DecryptionContext types, even though their contents and behavior are the same.
N/A
N/A
> Distinct Encryption/Decryption Contexts

- aws-lc-fips-sys/Cargo.toml
- aws-lc-fips-sys/src/linux_aarch64_crypto.rs
- aws-lc-fips-sys/src/linux_aarch64_crypto_ssl.rs
- aws-lc-fips-sys/src/linux_x86_64_crypto.rs
- aws-lc-fips-sys/src/linux_x86_64_crypto_ssl.rs
N/A
Update to latest from AWS-LC FIPS branch.
N/A
N/A
> Update aws-lc-fips-sys to v0.9.1

- .github/workflows/ci.yml
- Makefile
- aws-lc-rs/Makefile
- scripts/tools/copyright_check.sh
N/A
* Verify MSRV in our CI
* Fix copyright CI check
N/A
N/A
> Verify MSRV in CI

- .github/workflows/ci.yml
- aws-lc-rs/src/test.rs
N/A
* Fixing mirai CI
N/A
* Upgraded and ran `cargo mirai` locally.
> Upgrade Mirai version

- aws-lc-rs/src/digest.rs
- aws-lc-rs/src/error.rs
- aws-lc-rs/src/evp_pkey.rs
- aws-lc-rs/src/rsa.rs
Fixes all outstanding clippy nightly issues that have been identified.
> Fix identified clippy nightly issues

- aws-lc-rs/Cargo.toml
N/A
* Prepare for 1.3.0 release
N/A
N/A
> aws-lc-rs = '1.3.0'

- aws-lc-sys/Cargo.toml
- aws-lc-sys/src/linux_aarch64_crypto.rs
- aws-lc-sys/src/linux_aarch64_crypto_ssl.rs
- aws-lc-sys/src/linux_x86_64_crypto.rs
- aws-lc-sys/src/linux_x86_64_crypto_ssl.rs
- aws-lc-sys/src/linux_x86_crypto.rs
- aws-lc-sys/src/linux_x86_crypto_ssl.rs
- aws-lc-sys/src/macos_x86_64_crypto.rs
- aws-lc-sys/src/macos_x86_64_crypto_ssl.rs
N/A
* Patch release to fix Windows consumers.
N/A
N/A
> Patch release aws-lc-rs = v0.10.1

- aws-lc-fips-sys/Cargo.toml
- aws-lc-fips-sys/src/linux_aarch64_crypto.rs
- aws-lc-fips-sys/src/linux_aarch64_crypto_ssl.rs
- aws-lc-fips-sys/src/linux_x86_64_crypto.rs
- aws-lc-fips-sys/src/linux_x86_64_crypto_ssl.rs
- aws-lc-sys/Cargo.toml
N/A
* Update bindings for a patch revision.
N/A
* Generation script succeeds.
> aws-lc-fips-sys v0.10.1

- aws-lc-fips-sys/include/rust_wrapper.h
- aws-lc-fips-sys/src/linux_aarch64_crypto.rs
- aws-lc-fips-sys/src/linux_aarch64_crypto_ssl.rs
- aws-lc-fips-sys/src/linux_x86_64_crypto.rs
- aws-lc-fips-sys/src/linux_x86_64_crypto_ssl.rs
- aws-lc-sys/include/rust_wrapper.h
- aws-lc-sys/src/linux_aarch64_crypto.rs
- aws-lc-sys/src/linux_aarch64_crypto_ssl.rs
- aws-lc-sys/src/linux_x86_64_crypto.rs
- aws-lc-sys/src/linux_x86_64_crypto_ssl.rs
- aws-lc-sys/src/linux_x86_crypto.rs
- aws-lc-sys/src/linux_x86_crypto_ssl.rs
- aws-lc-sys/src/macos_x86_64_crypto.rs
- aws-lc-sys/src/macos_x86_64_crypto_ssl.rs
> Regenerate crates to support CRYPTO_tls1_prf

- aws-lc-rs/src/lib.rs
- aws-lc-rs/src/tls_prf.rs
- aws-lc-rs/src/tls_prf/tests/fips.rs
> TLS 1.2 PRF Support

- .github/codecov.yml
- .github/workflows/ci.yml
> Add Codecov Reports

- aws-lc-rs-testing/tests/quic_test.rs
- aws-lc-rs/src/aead.rs
- scripts/generate/_verify_crate_api_diff.sh
> Use stable for public-api diff, cleanup doc string

- aws-lc-rs/Cargo.toml
> Bump aws-lc-rs to v1.4.0

- aws-lc-rs/Cargo.toml
> Bump aws-lc-rs to v1.5.0

- aws-lc-rs/Cargo.toml
> Fix docs.rs generation failure due to build environment issues

- aws-lc-fips-sys/Cargo.toml
- aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols.h
- aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h
- aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc
- aws-lc-fips-sys/src/linux_aarch64_crypto.rs
- aws-lc-fips-sys/src/linux_aarch64_crypto_ssl.rs
- aws-lc-fips-sys/src/linux_x86_64_crypto.rs
- aws-lc-fips-sys/src/linux_x86_64_crypto_ssl.rs
- aws-lc-rs/Cargo.toml
- aws-lc-sys/Cargo.toml
- aws-lc-sys/generated-include/openssl/boringssl_prefix_symbols.h
- aws-lc-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h
- aws-lc-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc
- aws-lc-sys/src/linux_aarch64_crypto.rs
- aws-lc-sys/src/linux_aarch64_crypto_ssl.rs
- aws-lc-sys/src/linux_x86_64_crypto.rs
- aws-lc-sys/src/linux_x86_64_crypto_ssl.rs
- aws-lc-sys/src/linux_x86_crypto.rs
- aws-lc-sys/src/linux_x86_crypto_ssl.rs
- aws-lc-sys/src/macos_x86_64_crypto.rs
- aws-lc-sys/src/macos_x86_64_crypto_ssl.rs
> Bump version to v1.5.2

- .github/workflows/ci.yml
- aws-lc-rs/scripts/run-rustls-integration.sh
Now that rustls has gone through the effort to add aws-lc-rs as an optional feature, this updates our CI integration test to properly use the provided feature rather then our previous hack.
> Update rustls integration test

- aws-lc-rs/src/rsa.rs
- aws-lc-rs/src/rsa/key.rs
Cleaning up some remaining vestiges from the recent module refactor.
> RSA Module Tidying

- .github/workflows/ci.yml
- .github/workflows/deploy-user-guide.yml
> Migrate actions-rs/* to dtolnay/rust-toolchain

- aws-lc-rs/src/ec/key_pair.rs
- aws-lc-rs/src/key_wrap.rs
- aws-lc-rs/src/key_wrap/tests.rs
- aws-lc-rs/src/key_wrap/tests/fips.rs
> Minor adjustments to key_wrap module API

- .github/workflows/deploy-docs.yml
> Fix GH doc deploy

- .github/workflows/analysis.yml
- aws-lc-rs/Cargo.toml
- aws-lc-rs/Makefile
- aws-lc-rs/src/agreement.rs
- aws-lc-rs/src/ec.rs
- aws-lc-rs/src/ec/key_pair.rs
- aws-lc-rs/src/encoding.rs
- aws-lc-rs/src/kem.rs
- aws-lc-rs/src/rsa/key.rs
- aws-lc-rs/tests/ecdsa_tests.rs
N/A
* Macros to generate dedicated types for each encoding type.
N/A
N/A
> Encoding docs cleanup

- .github/workflows/deploy-docs.yml
> Fix doc deploy 2

- aws-lc-rs/src/ec.rs
- aws-lc-rs/src/encoding.rs
> Rename EcPublicKeyX509Der to PublicKeyX509Der

- aws-lc-rs/Cargo.toml
> Build doc.rs with unstable enabled

- aws-lc-fips-sys/Cargo.toml
- aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols.h
- aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h
- aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc
- aws-lc-fips-sys/src/linux_aarch64_crypto.rs
- aws-lc-fips-sys/src/linux_aarch64_crypto_ssl.rs
- aws-lc-fips-sys/src/linux_x86_64_crypto.rs
- aws-lc-fips-sys/src/linux_x86_64_crypto_ssl.rs
* Update aws-lc-fips-sys to 0.12.1
> Update aws-lc-fips-sys to 0.12.1

- aws-lc-rs/Cargo.toml
> Update aws-lc-rs to v1.6.2

- aws-lc-fips-sys/Cargo.toml
- aws-lc-sys/Cargo.toml
> aws-lc-sys-v0.13.1 and aws-lc-fips-sys-v0.12.2

- aws-lc-sys/Cargo.toml
- aws-lc-sys/generated-include/openssl/boringssl_prefix_symbols.h
- aws-lc-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h
- aws-lc-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc
- aws-lc-sys/src/linux_aarch64_crypto.rs
- aws-lc-sys/src/linux_aarch64_crypto_ssl.rs
- aws-lc-sys/src/linux_x86_64_crypto.rs
- aws-lc-sys/src/linux_x86_64_crypto_ssl.rs
- aws-lc-sys/src/linux_x86_crypto.rs
- aws-lc-sys/src/linux_x86_crypto_ssl.rs
- aws-lc-sys/src/macos_x86_64_crypto.rs
- aws-lc-sys/src/macos_x86_64_crypto_ssl.rs
* #353
* Update license metadata
> Update aws-lc-sys to 0.13.3

- aws-lc-rs/Cargo.toml
> aws-lc-rs v1.7.0

- .github/workflows/cross.yml
- aws-lc-fips-sys/builder/cmake_builder.rs
- aws-lc-sys/builder/cmake_builder.rs
* Adds CI to build/test for `x86_64-pc-windows-gnu`
* On Windows/x86_64, also check for NASM
> Add CI for testing x86_64-pc-windows-gnu

- .github/workflows/cross.yml
- scripts/ci/ios-simulator-runner.sh
Avoids regression on:
* #397
* Perform a release build when testing to help surface potential build failures.
> Build/test with `--release` build for MinGW, iOS

- .github/workflows/tests.yml
> Update to codecov-action@v4

- aws-lc-rs-testing/benches/kem_benchmark.rs
- aws-lc-rs/src/agreement.rs
- aws-lc-rs/src/cipher/chacha.rs
- aws-lc-rs/src/digest.rs
- aws-lc-rs/src/ec.rs
- aws-lc-rs/src/error.rs
- aws-lc-rs/src/hkdf.rs
- aws-lc-rs/src/io/der.rs
- aws-lc-rs/src/rand.rs
- aws-lc-rs/src/rsa/key.rs
- aws-lc-rs/src/rsa/signature.rs
- aws-lc-rs/src/test.rs
- aws-lc-rs/src/unstable/kem.rs
- aws-lc-rs/tests/aead_test.rs
- aws-lc-rs/tests/hmac_test.rs
- aws-lc-rs/tests/rsa_test.rs
- aws-lc-rs/util/process-criterion-csv.rs
* Various trivial code cleanups via RustRover's "Inspect Code".
> Trivial RustRover cleanups

- .github/workflows/cross.yml
- Cross.toml
* Resolves: #413
* https://github.com/aws/aws-lc/pull/1559
> CI for cross-compiling to x86_64-pc-windows-gnu

- .github/workflows/integration.yml
* Fix s2n-quic integration tests.
> Fix s2n-quic integ test

- .github/workflows/analysis.yml
- aws-lc-fips-sys/builder/bindgen.rs
- aws-lc-fips-sys/src/lib.rs
- aws-lc-rs/src/aead/tls.rs
- aws-lc-rs/src/cipher.rs
- aws-lc-rs/src/key_wrap.rs
- aws-lc-sys/builder/bindgen.rs
- aws-lc-sys/src/lib.rs
* Fix CI failures due to api-diff wanting `nightly-2024-06-07`.
* Fix various minor clippy findings.
> Update nightly for api-diff

- aws-lc-rs/Cargo.toml
* Preparing for a aws-lc-rs v1.7.3 release.
> Update aws-lc-rs to v1.7.3

- .github/workflows/analysis.yml
- .github/workflows/cross.yml
- .github/workflows/fips.yml
- .github/workflows/integration.yml
- .github/workflows/pregen-bindings.yml
- .github/workflows/tests.yml
* Minor cleanup/consistency changes for our GitHub workflows.
> GH workflow cleanup

- aws-lc-rs/Cargo.toml
Resolves:
* #427 
* #453 
Update aws-lc-rs to v1.8.1.
> Bump aws-lc-rs to v1.8.1

- .github/workflows/analysis.yml
- .github/workflows/cross.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/fips-bindings-generator.yml
- .github/workflows/fips.yml
- .github/workflows/integration.yml
- .github/workflows/pregen-bindings.yml
- .github/workflows/sys-bindings-generator.yml
- .github/workflows/tests.yml
* Fix "careful" CI.
* Return CI to using "nightly" toolchain.
> Fix careful CI; Return CI to nightly

- book/src/platform_support.md
* Update User Guide list of platforms for which we pregenerate bindings.
> Update User Guide pregen platforms

- aws-lc-rs/Cargo.toml
> Bump aws-lc-rs to v1.10.0

- .github/workflows/analysis.yml
- .github/workflows/misc-tests.yaml
* Add CI from this PR: https://github.com/aws/aws-lc/pull/1892
* Add CI for metadata check for "links" line in aws-lc-sys and aws-lc-fips-sys.
> CI checks on license and metadata

- aws-lc-sys/builder/cc_builder.rs
Addresses: 
* #556
The `-Wno-unused-parameter` option should only be used with GNU/Clang compilers.
> Fix MSVC compiler checks

- aws-lc-fips-sys/builder/cmake_builder.rs
- aws-lc-fips-sys/builder/main.rs
- aws-lc-rs/src/error.rs
- aws-lc-rs/tests/aead_test.rs
- aws-lc-sys/builder/cc_builder.rs
- aws-lc-sys/builder/cmake_builder.rs
- aws-lc-sys/builder/main.rs
* Fix the latest clippy lints.
> Fix latest clippy lints

- aws-lc-fips-sys/Cargo.toml
- aws-lc-fips-sys/builder/main.rs
- aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols.h
- aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h
- aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc
- aws-lc-fips-sys/include/rust_wrapper.h
- aws-lc-fips-sys/src/aarch64_apple_darwin_crypto.rs
- aws-lc-fips-sys/src/aarch64_unknown_linux_gnu_crypto.rs
- aws-lc-fips-sys/src/aarch64_unknown_linux_musl_crypto.rs
- aws-lc-fips-sys/src/x86_64_apple_darwin_crypto.rs
- aws-lc-fips-sys/src/x86_64_unknown_linux_gnu_crypto.rs
- aws-lc-fips-sys/src/x86_64_unknown_linux_musl_crypto.rs
* Adds `openssl/ocsp.h` for generation
* Emit the OpenSSL configuration defines
>  Regenerate aws-lc-fips-sys

- aws-lc-rs/README.md
- aws-lc-rs/src/lib.rs
- aws-lc-sys/README.md
Addresses CryptoAlg-2739
Describe current behavior and how your code changes that behavior. If there are no issues this pr is resolving, explain why this change is necessary.
> Add link to PQ documentation

- aws-lc-rs/Cargo.toml
> Bump aws-ls-rs to v1.11.0

- scripts/publish/_prepublish_checks.sh
* Fix publish script -- use nightly toolchain for clippy
> Use nightly toolchain for clippy

- aws-lc-rs/Cargo.toml
> Update to aws-lc-rs v1.11.1

- aws-lc-fips-sys/Cargo.toml
- aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols.h
- aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h
- aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc
- aws-lc-fips-sys/src/aarch64_apple_darwin_crypto.rs
- aws-lc-fips-sys/src/aarch64_unknown_linux_gnu_crypto.rs
- aws-lc-fips-sys/src/aarch64_unknown_linux_musl_crypto.rs
- aws-lc-fips-sys/src/x86_64_apple_darwin_crypto.rs
- aws-lc-fips-sys/src/x86_64_unknown_linux_gnu_crypto.rs
- aws-lc-fips-sys/src/x86_64_unknown_linux_musl_crypto.rs
Bump aws-lc-fips-sys to 0.12.15
* Manual commit: https://github.com/aws/aws-lc-rs/commit/8fdf80ab679ca6131776d81d068e452475124522
* Automated workflow: https://github.com/aws/aws-lc-rs/actions/runs/11974099934
> Bump aws-lc-fips-sys to 0.12.15

- aws-lc-rs/scripts/run-rustls-integration.sh
> Fix rustls integ test

- aws-lc-rs/Cargo.toml
> Bump aws-lc-rs to v1.12.1

- aws-lc-rs/Cargo.toml
> Fix metadata

- aws-lc-rs/Cargo.toml
- aws-lc-rs/src/rsa/key.rs
* #701 
Prepare for a v1.12.3 release
> Prepare release v1.12.3

- aws-lc-rs/Cargo.toml
> Prepare release v1.12.4

- .github/workflows/integration.yml
- aws-lc-rs/scripts/run-rustls-integration.sh
* For rustls integration, test against both latest commit and latest release.
* Due to changes in the name of features, the test against the latest release will currently fail.
> Update rustls integ test

- aws-lc-sys/builder/main.rs
Provide message that `BINDGEN_EXTRA_CLANG_ARGS` can be used.
> Document that BINDGEN_EXTRA_CLANG_ARGS can be used

- .github/workflows/integration.yml
- aws-lc-fips-sys/Cargo.toml
- aws-lc-fips-sys/builder/cmake_builder.rs
- aws-lc-sys/Cargo.toml
- aws-lc-sys/builder/cc_builder.rs
- aws-lc-sys/builder/cmake_builder.rs
Addresses #783
* Fix build failure when SSL feature is enabled.
* Fix handling of `CXX` environment variable.
* Add CI to verify build packaging w/ SSL feature
> Test packaging w/ SSL build

- aws-lc-rs/src/aead/quic.rs
> Fix clippy

- .github/workflows/cmake.yml
Update CI to test w/ CMake 4.0 release. (Previously we were testing with a release candidate.)
> Test w/ CMake 4.0 release

- .github/workflows/cross.yml
- aws-lc-sys/builder/cmake_builder.rs
- aws-lc-sys/builder/main.rs
- aws-lc-sys/builder/prebuilt-nasm.bat
Resolves #ISSUE-NUMBER1
Addresses #ISSUE-NUMBER2
Describe current behavior and how your code changes that behavior. If there are no issues this pr is resolving, explain why this change is necessary.
Point out areas that need special attention or support during the review process. Discuss architecture or design changes.
How is this change tested (unit tests, fuzz tests, etc.)? Are there any testing steps to be verified by the reviewer?
> Test msys2 w/ prebuilt-nasm

- .github/workflows/integration.yml
- Cargo.toml
- aws-lc-fips-sys/Cargo.toml
- aws-lc-fips-sys/builder/main.rs
- aws-lc-fips-sys/builder/sys_bindgen.rs
- aws-lc-rs-testing/Cargo.toml
- aws-lc-rs/Cargo.toml
- aws-lc-rs/src/cipher/aes.rs
- aws-lc-rs/src/digest.rs
- aws-lc-rs/src/ec.rs
- aws-lc-rs/src/evp_pkey.rs
- aws-lc-rs/src/hmac.rs
- aws-lc-rs/src/kem.rs
- aws-lc-rs/src/pqdsa.rs
- aws-lc-rs/src/pqdsa/key_pair.rs
- aws-lc-rs/src/ptr.rs
- aws-lc-rs/src/rsa/key.rs
- aws-lc-sys/Cargo.toml
- aws-lc-sys/builder/main.rs
- aws-lc-sys/builder/sys_bindgen.rs
- links-testing/Cargo.toml
Bump MSRV to 1.70.0 for our next release.
> Bump MSRV to 1.70.0

- .github/workflows/cross.yml
- .github/workflows/integration.yml
- scripts/ci/ios-simulator-runner.sh
Fix and refactor "ios-simulator-runner.sh"
> Fix + refactor "ios-simulator-runner.sh"

- aws-lc-rs/Cargo.toml
Prepare for aws-lc-rs v1.14.0.
> Prepare aws-lc-rs v1.14.0
