aws/aws-lc-rs

aws-lc-fips-sys/builder/bindgen.rs, aws-lc-sys/builder/bindgen.rs
=> Remove usage of deprecated rustfmt_bindings

aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/src/linux_aarch64_crypto.rs, aws-lc-fips-sys/src/linux_aarch64_crypto_ssl.rs, aws-lc-fips-sys/src/linux_x86_64_crypto.rs, aws-lc-fips-sys/src/linux_x86_64_crypto_ssl.rs, aws-lc-rs/Cargo.toml, aws-lc-sys/Cargo.toml, scripts/publish/_prepublish_checks.sh, scripts/publish/_publish_tools.sh, scripts/publish/publish-aws-lc-fips-sys.sh, scripts/publish/publish-aws-lc-sys.sh
* Modified the aws-lc-fips-sys crate publish logic to strip the `aws-lc/go.mod` file.
* Bump aws-lc-fips-sys to 0.7.1
=> Regenerate aws-lc-fips-sys@0.7.1

aws-lc-rs/README.md, aws-lc-rs/src/aead/quic.rs, aws-lc-rs/src/lib.rs
N/A
* Remove unnecessary indirection in the quic/new-mask operation.
* Minor tweaks to documentation
N/A
`make test` succeeded.
=> Remove quic/new_mask indirection

.github/workflows/ci.yml, Makefile, aws-lc-rs/Makefile, aws-lc-sys/Cargo.toml, aws-lc-sys/builder/bindgen.rs, aws-lc-sys/builder/main.rs, aws-lc-sys/src/lib.rs
N/A
* The build will automatically generate bindings when it finds that pre-generated bindings aren't available for current platform.
* This simplifies when `aws-lc-rs` is a transitive dependency and intermediary dependencies can't easily determine whether "bindgen" is needed.
N/A
* Tested on Mac, Linux and Windows hosts
=> Auto-generate bindings when needed

aws-lc-sys/CMakeLists.txt, aws-lc-sys/builder/main.rs, scripts/generate/_crate_test_build.sh, scripts/generate/_generate_bindings.sh
N/A
This change causes the build to only create `libssl` when the "ssl" feature is enabled. This improves overall build latency.
Before:
```
❯ time cargo build 
Compiling cc v1.0.79
Compiling libc v0.2.142
Compiling paste v1.0.12
Compiling dunce v1.0.4
Compiling cmake v0.1.50
Compiling aws-lc-sys v0.6.1 (/home/justsmth/repos/aws-lc-rs/aws-lc-sys)
Finished dev [unoptimized + debuginfo] target(s) in 11.36s
cargo build  54.37s user 8.81s system 554% cpu 11.395 total
```
After:
```
❯ time cargo build
Compiling cc v1.0.79
Compiling libc v0.2.142
Compiling paste v1.0.12
Compiling dunce v1.0.4
Compiling cmake v0.1.50
Compiling aws-lc-sys v0.6.1 (/home/justsmth/repos/aws-lc-rs/aws-lc-sys)
Finished dev [unoptimized + debuginfo] target(s) in 6.41s
cargo build  24.37s user 5.40s system 461% cpu …
```
=> aws-lc-sys: only build libssl if needed

aws-lc-rs/src/aead/quic.rs, aws-lc-rs/src/cipher.rs, aws-lc-rs/src/cipher/aes.rs
N/A
* The [`quic::HeaderProtectionKey::new_mask`](https://docs.rs/aws-lc-rs/1.0.2/aws_lc_rs/aead/quic/struct.HeaderProtectionKey.html#method.new_mask) function has the need to encrypt a single block of data. Our logic was invoking `AES_ecb_encrypt` but because only a single block is being encrypted, it should call `AES_encrypt`.
* The performance on AES128 is slightly better (by fractions of a nanosecond) and about the same for AES256:
```
QUIC-Aes128Gcm-new-mask-sample-16-bytes/AWS-LC
time:   [5.3600 ns 5.3634 ns 5.3670 ns]
change: [-6.0478% -5.7802% -5.5706%] (p = 0.00 < 0.05)
Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
3 (3.00%) low mild
1 (1.00%) high mild
2 (2.00%) high severe
QUIC-Aes256Gcm-new-mask-sample-16-bytes/AWS-LC
time:   [7.5755 ns 7.5818 ns …
```
=> Only AES_encrypt is needed

.github/workflows/ci.yml
N/A
* Change toolchain used for api-diff to recommended.
N/A
N/A
=> Use recommended toolchain for api-diff CI

Cargo.toml, aws-lc-rs/benches/cipher_benchmark.rs, aws-lc-rs/src/aead.rs, aws-lc-rs/src/aead/aes_gcm.rs, aws-lc-rs/src/aead/chacha.rs, aws-lc-rs/src/aead/key_inner.rs, aws-lc-rs/src/aead/quic.rs, aws-lc-rs/src/cipher.rs, aws-lc-rs/src/cipher/key.rs, aws-lc-rs/src/hkdf.rs, aws-lc-rs/src/hmac.rs, aws-lc-rs/tests/cipher_test.rs
N/A
* Renamed `DecryptionContext` to `CipherContext`
* Moved `SymmetricCipherKey` to a `key` sub-module.
* `impl AsRef<[u8]> for CipherContext`
* `#[derive(Debug, PartialEq, Eq, Clone, Copy)]` on simple enums.
* Add integ tests.
N/A
N/A
=> Minor cipher refactoring; Add integ tests

aws-lc-rs/src/cipher.rs, aws-lc-rs/src/iv.rs
N/A
* Zeroize the IVs after use.
N/A
N/A
=> Zeroize the IVs after use

aws-lc-rs/Cargo.toml, aws-lc-rs/examples/cipher.rs
```
$ cargo run --example cipher -- --mode ctr encrypt "Hello World"
key: b331133eb742497c67ced9520c9a7de3
iv: 4e967c7b799e0670431888e2e959e154
ciphertext: 88bcbd8d1656d60de739c5
$ cargo run --example cipher -- --mode ctr --key b331133eb742497c67ced9520c9a7de3 decrypt --iv 4e967c7b799e0670431888e2e959e154 88bcbd8d1656d60de739c5
Hello World
$ cargo run --example cipher -- --mode cbc encrypt "Hello World"
key: 6489d8ce0c4facf18b872705a05d5ee4
iv: 5cd56fb752830ec2459889226c5431bd
ciphertext: 6311c14e8104730be124ce1e57e51fe3
$ cargo run --example cipher -- --mode cbc --key 6489d8ce0c4facf18b872705a05d5ee4 decrypt --iv 5cd56fb752830ec2459889226c5431bd 6311c14e8104730be124ce1e57e51fe3
Hello World
```
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Add Cipher CLI example for CBC/CTR API

aws-lc-rs/src/cipher.rs, aws-lc-rs/src/iv.rs, aws-lc-rs/tests/cipher_test.rs
N/A
* Replace magic number in `Iv128(FixedLength<16>)`
* Add tests to cover missed `FixedLength` functions.
* Remove a couple unused functions
N/A
N/A
=> Improve test coverage

aws-lc-rs/src/cipher.rs
Removes:
* `impl TryFrom<PaddedBlockEncryptingKey> for EncryptingKey`
* `impl TryFrom<PaddedBlockDecryptingKey> for DecryptingKey`
These could have been used by a user to bypass our (intentional) limitation of not allowing a user to use CBC mode without padding.
=> Remove TryFrom conversions for padding to unpadded

aws-lc-rs/src/cipher.rs
See [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/documentation.html#examples-use--not-try-not-unwrap-c-question-mark)
=> Examples use `?`, not `try!`, not `unwrap`

aws-lc-rs/src/cipher.rs, aws-lc-rs/src/lib.rs, aws-lc-rs/tests/hkdf_test.rs
N/A
* Support HKDF for generation of UnboundCipherKey
* Make `AES_128` and `AES_256` "static".
* `impl Debug for UnboundCipherKey`
* Minor documentation tweaks.
N/A
Updated tests to cover HKDF for `UnboundCipherKey` and its Debug impl.
=> Support KKDF; Minor doc improvements

aws-lc-rs/src/cipher.rs, aws-lc-rs/src/iv.rs
In some cases our round-trip examples (where we just plug-in the IV immediately after having done an encryption operation) may not be clear on how you might actually use it in the real world where the IV is likely serialized to some data store for later usage.
=> Provide better documentation for CipherContext

aws-lc-rs/Cargo.toml, aws-lc-rs/benches/cipher_benchmark.rs
N/A
* Only run OpenSSL benchmarks when feature "openssl-benchmarks" is enabled.
N/A
N/A
=> Run openssl cipher-benchmarks with openssl-benchmarks feature

aws-lc-rs/examples/cipher.rs, aws-lc-rs/src/cipher.rs
N/A
* Change simplifies the params for the example CLI app -- either "encrypt" or "decrypt" are always first, then the options.
N/A
* Successfully ran the documented examples
=> CLI params for cipher example

aws-lc-rs/src/cipher.rs
Fixes some documentation that got dropped off from the enum macro change. Unfortunately using macro variables in documentation is not simple, so I have moved these examples to the module level documentation and simplified them.
=> Fix documentation issues

aws-lc-fips-sys/builder/main.rs, aws-lc-rs/build.rs, aws-lc-rs/src/digest.rs, aws-lc-rs/src/ed25519.rs, aws-lc-rs/src/hkdf.rs, aws-lc-rs/src/hmac.rs, aws-lc-rs/src/io/der.rs, aws-lc-rs/tests/aead_test.rs, aws-lc-sys/builder/main.rs
Resolves failures in the CI related to `clippy` tests
- Added # Panics section to functions that panic
- Remove unnecessary `vec!` constructs
- Remove unnecessary `iter()` calls
=> Add updates to fix CI

aws-lc-rs/README.md, aws-lc-rs/README.tpl, aws-lc-rs/src/debug.rs, aws-lc-rs/src/lib.rs
N/A
* Move "Contributor Quickstart" out of API documentations.  It's now further down in the README.
* The `derive_debug_via_id` macro should not have been exported.
N/A
N/A
=> Move 'Contributor Quickstart' out of API docs

aws-lc-rs/src/agreement.rs
N/A
Avoid the use of `unwrap()` in `agree_ephemeral`.
N/A
N/A
=> Avoid unwrap

.github/workflows/ci.yml, aws-lc-rs/Cross.toml, aws-lc-sys/builder/main.rs, docker/linux-cross/Dockerfile
N/A
* CI to cross-compile to 4 platforms: `aarch64-unknown-linux-gnu`, `i686-unknown-linux-gnu`, `powerpc64le-unknown-linux-gnu`, `riscv64gc-unknown-linux-gnu`
* We have a dev-dependency on `ring`, which doesn't support "powerpc64le" and "riscv64gc", so we're currently unable to run our tests on those platforms.
* We were already cross-compiling to `aarch64-unknown-linux-gnu` and `i686-unknown-linux-gnu` as part of the "aws-lc-rs tests" job.  I refactored the jobs so that all cross-compiling is done in "aws-lc-rs cross tests".
N/A
=> CI for cross-compilation

.github/workflows/ci.yml
N/A
* [Recent PR](https://github.com/aws/aws-lc-rs/pull/173) allowed an environment variable to force a static/dynamic build of AWS-LC
* This change adds CI that covers usage of this environment variable
N/A
N/A
=> Test with dynamic/static build

.github/workflows/ci.yml, scripts/tools/cargo-dig.rs, scripts/tools/semver.rs, scripts/tools/target-platform.rs
Migrate from `rust-script` to Cargo's nightly script feature.
=> Use nightly cargo feature for scripts

aws-lc-rs/tests/basic_aead_test.rs
```
warning: this argument is a mutable reference, but not used mutably
--> aws-lc-rs/tests/basic_aead_test.rs:136:57
|
136 | fn test_aead_append_within(config: &AeadConfig, in_out: &mut [u8]) -> Result<Vec<u8>, String> {
|                                                         ^^^^^^^^^ help: consider changing to: `&[u8]`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_pass_by_ref_mut
```
=> Address latest clippy warnings

aws-lc-rs/src/digest.rs, aws-lc-rs/src/digest/digest_ctx.rs, aws-lc-rs/src/ec.rs, aws-lc-rs/src/ec/key_pair.rs, aws-lc-rs/src/ptr.rs
```
ECDSA-32-P256-SHA256-FIXED-sign-128-bytes/AWS-LC
time:   [19.332 µs 19.335 µs 19.339 µs]
ECDSA-32-P256-SHA256-FIXED-verify-128-bytes/AWS-LC
time:   [54.084 µs 54.086 µs 54.088 µs]
Found 2 outliers among 100 measurements (2.00%)
1 (1.00%) high mild
1 (1.00%) high severe
ECDSA-48-P384-SHA384-FIXED-sign-128-bytes/AWS-LC
time:   [94.512 µs 94.517 µs 94.521 µs]
Found 6 outliers among 100 measurements (6.00%)
1 (1.00%) low severe
1 (1.00%) low mild
4 (4.00%) high mild
ECDSA-48-P384-SHA384-FIXED-verify-128-bytes/AWS-LC
time:   [220.85 µs 220.86 µs 220.87 µs]
Found 7 outliers among 100 measurements (7.00%)
4 (4.00%) high mild
3 (3.00%) high severe
```
```
ECDSA-32-P256-SHA256-FIXED-sign-128-bytes/AWS-LC
time:   [20.074 µs 20.078 µs 20.082 µs]
change: [+3.8506% +3.8808% +3.9101%] (p = 0.00 < …
```
=> Migrate ECDSA to FIPS Approved Functions

aws-lc-rs/src/digest.rs, aws-lc-rs/src/digest/sha.rs, aws-lc-rs/src/ec.rs, aws-lc-rs/src/evp_pkey.rs, aws-lc-rs/src/rsa.rs
```
RSA-1192-PKCS1-SHA256-sign-128-bytes/AWS-LC
time:   [607.64 µs 607.89 µs 608.15 µs]
Found 15 outliers among 100 measurements (15.00%)
7 (7.00%) low severe
1 (1.00%) low mild
3 (3.00%) high mild
4 (4.00%) high severe
RSA-1192-PKCS1-SHA256-verify-128-bytes/AWS-LC
time:   [27.770 µs 27.771 µs 27.773 µs]
Found 2 outliers among 100 measurements (2.00%)
1 (1.00%) low mild
1 (1.00%) high mild
Benchmarking RSA-1768-PKCS1-SHA256-sign-128-bytes/AWS-LC: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 9.4s, enable flat sampling, or reduce sample count to 50.
RSA-1768-PKCS1-SHA256-sign-128-bytes/AWS-LC
time:   [1.8436 ms 1.8476 ms 1.8528 ms]
Found 14 outliers among 100 measurements (14.00%)
3 (3.00%) high mild
11 (11.00%) high severe …
```
=> Migrate RSA to FIPS Approved Functions

aws-lc-rs-testing/Cargo.toml, aws-lc-rs-testing/benches/rsa_benchmark.rs
After the recent refactor in https://github.com/aws/aws-lc-rs/pull/189 I noticed you could not execute the RSA benchmarks in the `aws-lc-rs-testing` crate.
=> Fix rsa_benchmark from recent testing refactor

aws-lc-rs/Cargo.toml, aws-lc-rs/src/agreement.rs, aws-lc-rs/src/ec.rs, aws-lc-rs/src/ec/key_pair.rs, aws-lc-rs/src/evp_pkey.rs
```
Agreement-X25519/AWS-LC time:   [33.262 µs 33.266 µs 33.269 µs]
Found 5 outliers among 100 measurements (5.00%)
4 (4.00%) low mild
1 (1.00%) high severe
Agreement-P256/AWS-LC   time:   [59.261 µs 59.265 µs 59.268 µs]
Found 5 outliers among 100 measurements (5.00%)
1 (1.00%) low mild
4 (4.00%) high mild
Agreement-P384/AWS-LC   time:   [242.20 µs 242.21 µs 242.22 µs]
Found 4 outliers among 100 measurements (4.00%)
1 (1.00%) low mild
3 (3.00%) high mild
```
```
Agreement-X25519/AWS-LC time:   [33.586 µs 33.590 µs 33.594 µs]
change: [+0.9610% +0.9827% +1.0041%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
3 (3.00%) low mild
1 (1.00%) high mild
Agreement-P256/AWS-LC   time:   [59.677 µs 59.682 µs 59.686 µs]
change: [+0.6937% +0.7047% …
```
=> Migrate Agreement to FIPS Approved Functions

aws-lc-rs/src/aead.rs, aws-lc-rs/src/aead/aead_ctx.rs, aws-lc-rs/src/aead/aes_gcm.rs, aws-lc-rs/src/ptr.rs
Moves `EVP_AEAD_CTX` structure to be a heap allocation due to alignment expectations with regards to the [`evp_aead_ctx_st_state`](https://github.com/aws/aws-lc/blob/2d7715b1ebe300daf6a4864cb59404d232d78ab4/include/openssl/aead.h#L210) stored as a field within. Reported by [theli-ua](https://github.com/theli-ua) when implementing AES-GCM-SIV support.
=> Move EVP_AEAD_CTX to a heap allocated structure

aws-lc-rs/src/aead/aead_ctx.rs, aws-lc-rs/src/aead/poly1305.rs, aws-lc-rs/src/agreement.rs, aws-lc-rs/src/ec.rs, aws-lc-rs/src/error.rs, aws-lc-rs/src/hmac.rs
N/A
* Remove unnecessary/redundant pointer casts.
* Change `poly1305_state` wrapper to directly wrap the underlying type.
N/A
N/A
=> Remove unneeded calls to .cast()

aws-lc-rs/src/aead/aead_ctx.rs, aws-lc-rs/src/agreement.rs, aws-lc-rs/src/bn.rs, aws-lc-rs/src/ec.rs, aws-lc-rs/src/ec/key_pair.rs, aws-lc-rs/src/ed25519.rs, aws-lc-rs/src/evp_pkey.rs, aws-lc-rs/src/ptr.rs, aws-lc-rs/src/rsa.rs
Just cleans up the usage so they you don't need to specify `LcPtr<*mut T>` or `DetachableLcPtr<*mut T>` but can just say `LcPtr<T>` or `DetacableLcPtr<T>` similar to how `ConstPtr<T>` is already how that type functions.
=> Refactor LcPtr, DetachablePtr for readability

aws-lc-rs/src/aead.rs, aws-lc-rs/src/aead/aead_ctx.rs, aws-lc-rs/src/aead/aes_gcm.rs, aws-lc-rs/src/aead/chacha.rs, aws-lc-rs/src/aead/chacha20_poly1305_openssh.rs, aws-lc-rs/src/aead/poly1305.rs
Initial pass at proposed AEAD APIs that can be used in a FIPS strict compliance mode. Leaving this as draft as more test cases will needed to be added, and I wanted to seek feedback on the current API direction.
In particular I think `TLSSealingKey` and `TLSOpeningKey` require some conversation. Right now they both take the `Nonce` argument and rely on the user to construct the argument to meeting the protocol requirements for TLS1.2 or TLS1.3. AWS-LC just enforces that the nonce is incremented sequentially. We could offer wrapping types that handle the nonce calculation by giving the initialization vector on key construction, and having the user pass the current sequence number, and doing the once computation for the user. This would mean that we would be exposing TLS protocol …
=> FIPS AEAD API Types

aws-lc-rs-testing/benches/hkdf_benchmark.rs, aws-lc-rs/src/hkdf.rs
Current HKDF API is a slightly difficult to map onto the AWS-LC FIPS API. The standalone `HDKF_expand` API is meant to be used with a KDF Feedback design mode as specified in [SP 800-108 section 4.2](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-108r1.pdf). In AWS-LC this function will set the FIPS indicator based on the digest algorithm and nothing else.
The other usage for KDF is defined in [SP 800-56C section 5](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Cr2.pdf) for key derivation (like a key agreement scheme) where the extraction and expansion are performed together as a single procedure.
The aws-lc-rs provides a mixed usage of both, even if the net outcome is the same. This is due to the `hkdf::Prk::new_less_safe` providing a construction …
=> Refactor HKDF for FIPS

aws-lc-rs/src/aead.rs, aws-lc-rs/src/aead/aead_ctx.rs, aws-lc-rs/src/aead/aes_gcm.rs, aws-lc-rs/tests/aead_test.rs
The current AEAD encrypt API takes a `in_out: &mut [u8]`, which forces callers to copy all of the cleartext into a single slice. This shouldn't be needed since encrypting a payload _is_ copying the data since it has to XOR it with the cipher stream. 
Luckily, AWS-LC already provides a EVP API to account for this: [EVP_AEAD_CTX_seal_scatter](https://docs.rs/aws-lc-sys/latest/aws_lc_sys/fn.EVP_AEAD_CTX_seal_scatter.html). This allows the caller to pass a `extra_in`, which is encrypted into the `tag_out` buffer.
In transport protocols like TLS and QUIC, where the bulk of the data being encrypted is separate from the framing header, using this API can yield large wins. In the case of s2n-quic, we see a reduction in 8% of CPU by avoiding the copy.
This new API isn't the most straightforward …
=> feat: add AEAD seal_in_place_scatter method

docker/linux-386/Dockerfile, docker/linux-arm64/Dockerfile, docker/linux-x86_64/Dockerfile
N/A
* The "sparse-registry" config in arm64 image is [no longer needed](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html#sparse-by-default-for-cratesio).
* Docker images were inconsistent at to whether:
* to install nightly
* to set CC/CXX
N/A
Using for sys crate updates.
=> Make docker configs consistent

.github/workflows/ci.yml, aws-lc-fips-sys/Cargo.toml, aws-lc-sys/Cargo.toml
N/A
* Our package configurations were not including the "*.asm" files for Windows x86 and x86-64.
* Added a CI for a `cargo publish --dry-run` step on Linux, Macos and Windows.
* Found while investigating: https://github.com/aws/aws-lc-rs/issues/225
I verified that the files are now included in our package:
```
❯ find ./target/package -name "chacha-*.asm" 
./target/package/aws-lc-fips-sys-0.10.0/aws-lc/generated-src/win-x86_64/crypto/chacha/chacha-x86_64.asm
./target/package/aws-lc-fips-sys-0.10.0/aws-lc/generated-src/win-x86/crypto/chacha/chacha-x86.asm
./target/package/aws-lc-sys-0.10.0/aws-lc/generated-src/win-x86_64/crypto/chacha/chacha-x86_64.asm
./target/package/aws-lc-sys-0.10.0/aws-lc/generated-src/win-x86/crypto/chacha/chacha-x86.asm
```
By submitting this pull request, I confirm …
=> Include Windows '*.asm' assembly files

aws-lc-rs/src/ed25519.rs, aws-lc-rs/tests/ed25519_tests.rs
To be consistent with other key generation strategies introduced on the fips-api-changes branch, migrate Ed25519 key-generation, and remove support for using the SecureRandom trait.
=> Migrate Ed25519 key generation to EVP_PKEY_keygen

.github/workflows/ci.yml, aws-lc-rs/src/digest.rs, aws-lc-rs/src/test.rs
N/A
* Fix clippy complaints regarding `[should_panic]`.
N/A
N/A
=> Clippy: fix 'should_panic' lints

.github/workflows/deploy-user-guide.yml, aws-lc-rs/src/aead.rs, aws-lc-rs/src/aead/chacha20_poly1305_openssh.rs, aws-lc-rs/src/aead/nonce_sequence.rs, aws-lc-rs/src/aead/nonce_sequence/counter32.rs, aws-lc-rs/src/aead/quic.rs, aws-lc-rs/src/aead/tests/fips.rs, aws-lc-rs/src/agreement.rs, aws-lc-rs/src/cipher.rs, aws-lc-rs/src/constant_time.rs, aws-lc-rs/src/digest.rs, aws-lc-rs/src/ec/key_pair.rs, aws-lc-rs/src/ed25519.rs, aws-lc-rs/src/error.rs, aws-lc-rs/src/hkdf.rs, aws-lc-rs/src/hmac.rs, aws-lc-rs/src/iv.rs, aws-lc-rs/src/lib.rs, aws-lc-rs/src/pbkdf2.rs, aws-lc-rs/src/rand.rs, aws-lc-rs/src/rsa.rs, aws-lc-rs/src/signature.rs, aws-lc-rs/src/signature/tests/fips/keys.rs, aws-lc-rs/src/test.rs
Add & Cleanup Documentation
* Fixed naming of types with `TLS` prefix to `Tls` following API guidelines. 
=> FIPS Usage Documentation

.github/workflows/ci.yml
N/A
* Add a Linux/arm32 target to our cross-compilation tests.
* Due to failing riscv64gc build, use Rust 1.72.1 from cross-compilation until resolved.
N/A
Successfully cross-compiled locally the affected platforms.
=> Add arm32; Rust 1.72.1 for cross-compile

aws-lc-sys/Cargo.toml, aws-lc-sys/tests/sanity-tests.rs
N/A
Remove openssl from aws-lc-sys's dev-dependencies. (The `aws-lc-rs-testing` package build links to both aws-lc-sys and openssl to verify there are no symbol conflicts.)
N/A
N/A
=> Remove openssl as dev-dependency

aws-lc-rs/src/aead.rs, aws-lc-rs/src/aead/chacha20_poly1305_openssh.rs, aws-lc-rs/src/agreement.rs, aws-lc-rs/src/cipher.rs, aws-lc-rs/src/digest.rs, aws-lc-rs/src/ec/key_pair.rs, aws-lc-rs/src/ed25519.rs, aws-lc-rs/src/hkdf.rs, aws-lc-rs/src/hmac.rs, aws-lc-rs/src/pbkdf2.rs, aws-lc-rs/src/rand.rs, aws-lc-rs/src/rsa.rs, aws-lc-rs/src/signature.rs, aws-lc-rs/src/tls_prf.rs
=> Documentation cleanup

aws-lc-rs/src/ec.rs, aws-lc-rs/src/ec/key_pair.rs
N/A
* Validate a public EC key at time of creation.
* Construct `LcPtr` instead of `DetachableLcPtr`.
N/A
Tests pass locally
=> Validate EC_KEY created from public point

aws-lc-rs-testing/benches/kem_benchmark.rs, aws-lc-rs/src/kem.rs, aws-lc-rs/tests/kem_tests.rs
Took a pass at cleaning up the types to remove the module stutter (and to be consistent with other project modules), reduced the scope of `unsafe` blocks, took a pass at the documentation.
=> KEM: Cleanup Types and Documentation

.github/workflows/ci.yml
N/A
* Add M1 Mac testing to our CI.
* See [recent GitHub blog post](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/) and [runner documentation](https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners).
N/A
N/A
=> Setup CI to use M1 (aarch64) Mac

aws-lc-rs/src/aead.rs, aws-lc-rs/src/aead/rand_nonce.rs, aws-lc-rs/src/aead/tls.rs, aws-lc-rs/src/aead/unbound_key.rs, aws-lc-rs/src/test.rs, aws-lc-rs/tests/aead_test.rs
In #206, we added a method that avoids copying data into a target buffer when performing an AEAD sealing operation.
This PR adds a corresponding method for AEAD opening. It works by decrypting the provided ciphertext into a destination output cleartext slice.
Note that I moved all of the EVP calls to associated methods on the `UnboundKey`, rather than being spread across the `aead` module as well as `aead::aes_gcm`.
I've refactored the AEAD tests a bit to test all of the supported permutations of sealer and opener functions, since the current form was getting more complicated. Note that SIV algorithms don't currently support scatter/gather operations.
=> feat: add AEAD open_separate_gather method

aws-lc-rs/src/digest.rs
In 0.17, ring made the `digest::Algorithm` fields private and changed them to getter functions:
https://github.com/briansmith/ring/commit/a26925cd1efd323a3ff6f8daf13a197caa3c179e
This change keeps the fields public (to avoid breaking changes) and also includes the functions.
=> fix: improve ring compat for digest::Algorithm

Cargo.toml, aws-lc-sys-testing/Cargo.toml, aws-lc-sys-testing/build.rs, aws-lc-sys-testing/src/main.rs, aws-lc-sys-testing/src/testing.c, aws-lc-sys/Cargo.toml, aws-lc-sys/builder/main.rs
The `aws-lc-sys` crate does not currently set the `links` attribute in the Cargo.toml. This prevents other crates from reading the `include` path and using it in other C libraries.
This change adds the `links` attribute and adds an integration test to ensure this functionality is preserved.
I did not refactor the `aws-lc-fips-sys` crate. There's quite a bit of copy/paste between the build scripts and could probably use a refactor.
I've added an integration test crate (`aws-lc-sys-testing`) showing that the change is now working and will be preserved in the future.
=> fix(aws-lc-sys): add `links` attribute to Cargo.toml

scripts/generate/_collect_symbols_build.sh
https://github.com/aws/aws-lc/pull/1309 wires up a new Ed25519 backend adding a new set of symbols with a prefix not captured by the current filter script. Add a rule that captures these symbols and filters them out, since they don't have external linkage.
See problematic linkage here: https://github.com/aws/aws-lc/actions/runs/6921644361/job/18827482208?pr=1309
=> Filter out edwards25519 symbls which are not supposed to have external linkage

aws-lc-fips-sys/Cargo.toml, aws-lc-sys/Cargo.toml
We are using `CopyOptions::skip_exist()` introduced in 1.3.
This fixes the build for any downstream crates that test that the minimum versions in their Cargo.toml cover the APIs that they rely on (using `cargo update -Z minimal-versions`).
Note that rustls isn't one of those any more; we just moved to `-Z direct-minimal-versions`: see [docs](https://doc.rust-lang.org/cargo/reference/unstable.html#minimal-versions)). Therefore, this fix isn't blocking us.
#284 would defend/validate this change.
I manually ran:
```shell
$ cargo +nightly update -Z minimal-versions
$ cargo --locked check
```
Prior to this fix; this fails with:
```
error[E0599]: no method named `skip_exist` found for struct `fs_extra::dir::CopyOptions` in the current scope
--> aws-lc-fips-sys/builder/main.rs:432:18
|
431 | …
```
=> Specify minimum required fs_extra as 1.3

.github/workflows/ci.yml, aws-lc-rs/Cargo.toml
Resolves https://github.com/aws/aws-lc-rs/issues/284
* CI to verify minimal dependency version are actually supported.
N/A
N/A
=> CI for minimal dependency versions

aws-lc-rs/src/agreement.rs, aws-lc-rs/src/ec.rs, aws-lc-rs/src/ed25519.rs, aws-lc-rs/src/hex.rs, aws-lc-rs/src/lib.rs, aws-lc-rs/src/rsa.rs, aws-lc-rs/src/signature.rs, aws-lc-rs/src/test.rs
N/A
* Refactor hex encode/decode logic into its own `hex` module.
* Still expose these functions publicly from the `test` module.
N/A
N/A
=> Move hex functions out of test mod

aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/builder/main.rs, aws-lc-sys/Cargo.toml, aws-lc-sys/builder/main.rs
N/A
* Pregenerated bindings for Linux were generated using glibc.  Need to generate/test bindings for other environments (like musl).
N/A
N/A
=> Consider target env for pregenerated bindings

.github/workflows/ci.yml, aws-lc-rs/src/aead/chacha20_poly1305_openssh.rs, aws-lc-rs/src/aead/nonce.rs, aws-lc-sys/builder/main.rs
N/A
* Fix bug in Nonce construction affecting big-endian CPUs.
* Impl `From<&[BigEndian<u32>; 3]>` and `From<&[LittleEndian<u32>; 3]>` for Nonce
* Add CI for powerpc and powerpc64 (big-endian).
* Current behavior when converting a`[u32; 3]` to a Nonce implicitly assumes the `u32` values are `LittleEndian`. To avoid ambiguity, it's better for the endian-ness of the values to be explicit. This PR (attempts to) mark the existing implicit implementation as deprecated in favor of new explicit alternatives.
* Tests succeed locally on Linux host.  The cross-compilation of the tests on Mac host has a link failure.
=> Support for PowerPC big-endian

aws-lc-fips-sys/builder/main.rs, aws-lc-sys/builder/main.rs
N/A
Set the debug flags for CMake when we run a "debug" build.
N/A
N/A
=> Set debug for CMAKE_BUILD_TYPE

aws-lc-rs/src/aead/chacha20_poly1305_openssh.rs, aws-lc-rs/src/aead/nonce.rs, aws-lc-rs/src/endian.rs
N/A
* Improve support for big/little-endian arrays.
* `FromByteArray` was previously unused. I renamed/repurposed it.
* Although these traits/functions are `pub` they are not (yet) visible outside the crate. These could potentially be useful to our consumers.
* Added/updated unit tests. 
=> Improve support for big/little-endian arrays

aws-lc-fips-sys/CMakeLists.txt, aws-lc-sys/CMakeLists.txt
The multiline comment at the top of `CMakeLists.txt` is only supported by CMake 3.0+. This means the `cmake_minimum_required(VERSION 3.0)` check on subsequent lines is not reached when using older versions of CMake, so you end up with an error such as:
```
Parse error.  Expected "(", got unquoted argument with text "Amazon.com,".
```
This change switches to using comments supported by older versions of CMake so the `cmake_minimum_required` can produce a more useful error message.
CI
=> Use classic comment style for CMakelists copyright notice

aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-fips-sys/builder/main.rs, aws-lc-sys/builder/cmake_builder.rs, aws-lc-sys/builder/main.rs
N/A
* Refactor CMake-specific build logic into a separate module.
* Updated both aws-lc-sys and aws-lc-fips-sys.
* Created a `Builder` trait to provide an abstraction.
N/A
=> Refactor sys-crate Cmake build logic

aws-lc-rs/src/key_wrap/tests/fips.rs, scripts/tools/cargo-dig.rs, scripts/tools/copyright_check.sh, scripts/tools/semver.rs
Cargo nightly is experimenting with a different syntax for the Cargo manifest description in scripts (they eliminated `//!` usage). So for now update to the one documented [here](https://doc.rust-lang.org/cargo/reference/unstable.html#script). There are a few other contenders that are not officially documented, but going with the one publicly visible for now.
May break again if they land on a different syntax for the manifest portion.
=> Fix script nightly feature

.github/workflows/fips.yml, aws-lc-fips-sys/CMakeLists.txt, aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-fips-sys/builder/main.rs, aws-lc-fips-sys/builder/printenv.bat, aws-lc-fips-sys/include/rust_wrapper.h, aws-lc-sys/CMakeLists.txt, aws-lc-sys/builder/cmake_builder.rs, aws-lc-sys/builder/main.rs, aws-lc-sys/include/rust_wrapper.h
N/A
* A working FIPS build for Windows.
* This change uses a Windows batch script to execute `vcvarsall.bat` and then display all of the environment variables that were set.
* Our build-script parses environment variables from the output of the script and sets those variables to be available for CMake.
N/A
* Test succeeded on my Windows host.
=> A working FIPS build for Windows

.github/workflows/analysis.yml, .github/workflows/cross.yml, .github/workflows/deploy-docs.yml, .github/workflows/fips.yml, .github/workflows/integration.yml, .github/workflows/tests.yml
N/A
* Public rustdocs to our `gh-pages` branch
* Configure most CI workflow jobs to only run for "aws/aws-lc-rs"
* Except these which still run on forks: `rustfmt`, `clippy`, `dependency-review`, `msrv`, `copyright`, `semver-checks` and `aws-lc-rs-coverage`
N/A
N/A
=> Rust Docs + GH workflow cleanup

.github/workflows/fips.yml, .github/workflows/integration.yml, .github/workflows/tests.yml, aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-fips-sys/builder/printenv.bat
N/A
* For the Windows/FIPS build, add fallback logic for locating `vcvarsall.bat` when `vswhere.exe` fails.
* Increase verbosity of failures.
N/A
* I'm still not sure of the root cause for the [build failure seen here](https://github.com/rustls/rustls/actions/runs/7694846379/job/20966481181?pr=1732#step:7:205).  However, this change should provide more logging to diagnose the issue.
=> Improve how vcvarsall is located

.github/workflows/integration.yml, .github/workflows/tests.yml
N/A
* Separate CI tasks to dry-run publish each crate independently.
*  We were previously lumping all 3 crates into a single task, and then ignoring the expected failure b/c `aws-lc-rs` depended on not-yet-released versions of our sys crates.
* Motivated by #332 where we forgot to include a Windows-specific file in the crate we published.
=> Improve exposure of dry-run publish failures

.github/workflows/cross.yml
Use `stable` toolchain for CI cross-compilation tests.
`riscv64` still stuck at 1.72.1 due to link failure.
```
unsupported ISA subset `z'
```
=> Use stable toolchain for CI cross-compilation

.github/workflows/analysis.yml
=> Fix CI analysis workflow

aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/LICENSE, aws-lc-sys/Cargo.toml, aws-lc-sys/LICENSE
* #353 
* Update metadata for sys-crate license. The sys-crates contain code from AWS-LC.
=> Update license metadata for sys-crates

aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc, aws-lc-fips-sys/src/linux_aarch64_crypto.rs, aws-lc-fips-sys/src/linux_aarch64_crypto_ssl.rs, aws-lc-fips-sys/src/linux_x86_64_crypto.rs, aws-lc-fips-sys/src/linux_x86_64_crypto_ssl.rs, aws-lc-fips-sys/symbols/linux_aarch64.txt, scripts/generate/_collect_symbols_build.sh
* Our crate generation scripts were preventing `OPENSSL_armcap_P` from being prefixed.  The issue has been fixed upstream, and this is no longer needed.
=> Update aws-lc-fips-sys to 0.12.5

.github/workflows/analysis.yml, aws-lc-rs/src/rsa/key.rs, aws-lc-rs/tests/basic_aead_test.rs
* Minor cleanup of `use` and `mut`
* Also run clippy CI with `--no-default-features`
=> Minor cleanup; clippy w/ no features

scripts/generate/_generate_all_bindings_flavors.sh, scripts/generate/_generation_tools.sh, scripts/generate/_run_supported_symbol_builds.sh, scripts/generate/_test_supported_builds.sh, scripts/generate/generate-aws-lc-sys.sh, scripts/publish/_publish_tools.sh, scripts/publish/publish-aws-lc-fips-sys.sh, scripts/publish/publish-aws-lc-sys.sh
* Add check to sys-crate publishing script to verify expected prefix.
* Fix how generation scripts check for macOS.
* Remove generation script expectation that we're on main.
* Other cleanup in generation scripts.
Tested on macos and linux hosts
=> Add check for sys crate publish; Script cleanup

aws-lc-fips-sys/builder/main.rs, aws-lc-sys/builder/main.rs
* We are sending `cargo:rerun-if-env-changed` to stderr, but cargo commands should be [sent to stdout](https://doc.rust-lang.org/cargo/reference/build-scripts.html#life-cycle-of-a-build-script).
=> Build scripts send cargo cmds to stdout

.github/workflows/analysis.yml, aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/builder/main.rs, aws-lc-sys/Cargo.toml, aws-lc-sys/builder/main.rs
* Fix bindgen dependency configuration
=> Fix bindgen dependency cfg

aws-lc-rs/Cargo.toml
=> Update aws-lc-rs to v1.6.4

aws-lc-sys/Cargo.toml, aws-lc-sys/generated-include/openssl/boringssl_prefix_symbols.h, aws-lc-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h, aws-lc-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc, aws-lc-sys/src/aarch64_apple_darwin_crypto.rs, aws-lc-sys/src/aarch64_apple_darwin_crypto_ssl.rs, aws-lc-sys/src/aarch64_unknown_linux_gnu_crypto.rs, aws-lc-sys/src/aarch64_unknown_linux_gnu_crypto_ssl.rs, aws-lc-sys/src/aarch64_unknown_linux_musl_crypto.rs, aws-lc-sys/src/aarch64_unknown_linux_musl_crypto_ssl.rs, aws-lc-sys/src/i686_unknown_linux_gnu_crypto.rs, aws-lc-sys/src/i686_unknown_linux_gnu_crypto_ssl.rs, aws-lc-sys/src/x86_64_apple_darwin_crypto.rs, aws-lc-sys/src/x86_64_apple_darwin_crypto_ssl.rs, aws-lc-sys/src/x86_64_unknown_linux_gnu_crypto.rs, aws-lc-sys/src/x86_64_unknown_linux_gnu_crypto_ssl.rs, aws-lc-sys/src/x86_64_unknown_linux_musl_crypto.rs, aws-lc-sys/src/x86_64_unknown_linux_musl_crypto_ssl.rs
* Update aws-lc-sys to v0.14.1
* Bindings generated by this run: https://github.com/aws/aws-lc-rs/actions/runs/8529098580
=> Update aws-lc-sys to v0.14.1

aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc, aws-lc-fips-sys/src/aarch64_apple_darwin_crypto.rs, aws-lc-fips-sys/src/aarch64_apple_darwin_crypto_ssl.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_gnu_crypto.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_gnu_crypto_ssl.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_musl_crypto.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_musl_crypto_ssl.rs, aws-lc-fips-sys/src/x86_64_apple_darwin_crypto.rs, aws-lc-fips-sys/src/x86_64_apple_darwin_crypto_ssl.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_gnu_crypto.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_gnu_crypto_ssl.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_musl_crypto.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_musl_crypto_ssl.rs
* Update aws-lc-fips-sys to v0.12.7
* Bindings generated by this run: https://github.com/aws/aws-lc-rs/actions/runs/8529121080
=> Update aws-lc-fips-sys to v0.12.7

.github/workflows/cross.yml, aws-lc-sys/builder/cmake_builder.rs
Resolves #373 
* Fixes CMake build when compiling to `x86_64-apple-ios`.
* Adds CI step for this build.
=> Support target x86_64-apple-ios

.github/workflows/cross.yml, aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-sys/builder/cmake_builder.rs
* Add `s390x-unknown-linux-gnu` target to our CI.
* Removes no longer needed `ENABLE_EXPERIMENTAL_BIG_ENDIAN_SUPPORT` build flag.
* s390x listed [here](https://github.com/aws/aws-lc?tab=readme-ov-file#other-platforms).
=> Include s390x in CI

.github/workflows/tests.yml, aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-fips-sys/builder/main.rs, aws-lc-sys/builder/cmake_builder.rs, aws-lc-sys/builder/main.rs
* Provides workaround for #376 (or for other platforms where AWS-LC assembly fails to build)
* AWS-LC contains optimized assembly language implementations for many primitive cryptographic operations. As a fall-back, these operations also have a C-implementation provided.
* For most platforms, CMake correctly detects whether/which assembly files should be built. However, CMake's detection is sometimes inadequate or the build environment lacks an assembler (such as NASM), and the `OPENSSL_NO_ASM` flag must be passed to avoid build failures.
* The `OPENSSL_NO_ASM` flag may also be useful for debugging failing cryptographic operations.
* The C-implementations are significantly slower than their assembly-language counterparts.
* The `OPENSSL_NO_ASM` flag is only allowed for un-optimized/debug …
=> ENV vars for OPENSSL_NO_ASM

aws-lc-rs/src/hkdf.rs
Hi there,
I've been working on [encrypted client hello (ECH)](https://datatracker.ietf.org/doc/html/draft-ietf-tls-esni-18) support [in Rustls](https://github.com/rustls/rustls/pull/1718). As part of that we're using aws-lc-rs for the HKDF operations the draft calls for.
In particular, ECH offer confirmation is determined by [computing an 8 byte confirmation value](https://datatracker.ietf.org/doc/html/draft-ietf-tls-esni-18#section-7.2):
```
accept_confirmation = HKDF-Expand-Label(
HKDF-Extract(0, ClientHelloInner.random),
"ech accept confirmation",
transcript_ech_conf,
8)
```
Similarly, in the [hello-retry request confirmation case](https://datatracker.ietf.org/doc/html/draft-ietf-tls-esni-18#section-7.2.1) we compute:
```
hrr_accept_confirmation = HKDF-Expand-Label(
HKDF-Extract(0, …
```
=> hkdf: increase MAX_HKDF_INFO_LEN

aws-lc-rs/scripts/run-rustls-integration.sh
* Fix rustls CI integration tests
=> Fix Rustls integ test

aws-lc-rs/scripts/run-s2n-quic-integration.sh
* Updating the s2n-quic integration test to align with its current build configuration.
=> Update s2n-quic integration test

.github/workflows/cross.yml, .github/workflows/fips.yml, .github/workflows/integration.yml, aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/builder/main.rs, aws-lc-fips-sys/src/lib.rs, aws-lc-rs-testing/Cargo.toml, aws-lc-rs/Cargo.toml, aws-lc-rs/src/agreement/ephemeral.rs, aws-lc-rs/tests/hmac_test.rs, aws-lc-sys/Cargo.toml, aws-lc-sys/builder/main.rs, aws-lc-sys/src/lib.rs
* Remove last remaining usage of `actions-rs` GitHub action.
* Fix riscv cross-compilation -- download latest to build cross, then download toolchain for target.
* Bump MSRV to 1.63 -- [Rustls is now at 1.63](https://github.com/rustls/rustls/blob/main/rustls/Cargo.toml#L5) as well.
* Ignoring the `unexpected_cfgs`. We can't properly handle these until we're at MSRV 1.77.
* Remove various erroneous reference to non-existent `cfg` values.
=> Cleanup CI and build configs

aws-lc-rs/src/cipher.rs, aws-lc-rs/src/cipher/padded.rs
* Without changing the public API, this change moves much of the implementation for padded block ciphers to its own sub-module.
* Prepare for the use of `EVP_CIPHER_CTX` for streaming operations:
* Refactor of `UnboundCipherKey` to delay the creation of the `SymmetricCipherKey` (or `EVP_CIPHER_CTX` until it's "bound" to an operation-specific key.
* This is the start of the work toward supporting for a "streaming" cipher modality (re: #396).  
=> Refactor Step 1 - move "padded" cipher implementation to sub-module

aws-lc-rs/util/process-criterion-csv.rs, scripts/tools/cargo-dig.rs, scripts/tools/semver.rs
* Recent change in (unstable) rust-script syntax is causing CI to fail in AWS-LC: https://github.com/aws/aws-lc/actions/runs/9018402921/job/24778943885?pr=1569
* This was apparently cause by this recent change: https://github.com/rust-lang/cargo/pull/13861
=> Fix recent change to rust-script syntax

.github/workflows/cross.yml, aws-lc-sys/builder/cmake_builder.rs
Resolves:
* #376
* Fixes build for `aarch64-pc-windows-msvc `. It requires that [clang-cl](https://learn.microsoft.com/en-us/cpp/build/clang-support-msbuild?view=msvc-170) and [ninja](https://github.com/ninja-build/ninja/releases) be installed.
* Verified locally that tests pass on a Windows/ARM64 host.
=> Support build for aarch64-pc-windows-msvc

aws-lc-rs/Cargo.toml, aws-lc-rs/src/hkdf.rs, aws-lc-rs/tests/hkdf_test.rs
* Remove arbitrary HKDF limit on the number of info bytes.
=> Remove arbitrary HKDF info length limit

.github/workflows/analysis.yml, .github/workflows/cross.yml, .github/workflows/deploy-docs.yml, .github/workflows/fips-bindings-generator.yml, .github/workflows/fips.yml, .github/workflows/integration.yml, .github/workflows/sys-bindings-generator.yml, .github/workflows/tests.yml, scripts/tools/cargo-dig.rs
Unblocks #aws/aws-lc#1612
Pin to Rust nightly toolchain `nightly-2024-05-22`.
=> Pin to nightly-2024-05-22

aws-lc-rs/util/process-criterion-csv.rs, scripts/tools/semver.rs, scripts/tools/target-platform.rs
* The rust-scripts needed to be pinned as well.
=> Pin rust-scripts

aws-lc-rs/src/cbb.rs, aws-lc-rs/src/ptr.rs
* Ensuring we have a `mut` reference when providing a `mut` pointer.
=> Cleanup use of mut ptr

.github/workflows/cross.yml, Cross.toml, docker/linux-cross/Dockerfile
Resolves #428
* Install/Use bindgen-cli inside container when cross-compiling with cross-rs.
* Added target `armv7-unknown-linux-gnueabihf`
* I changed the order of the CI targets to be sorted by name.
=> Cross-compile using bindgen-cli

.github/workflows/cross.yml, aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-sys/builder/cmake_builder.rs
Resolves #376
* [cargo-xwin](https://github.com/rust-cross/cargo-xwin) is a build tool for "Cross compil[ing a] Cargo project to Windows msvc target with ease".
* cargo-xwin sets a `CMAKE_TOOLCHAIN_FILE_*_pc_windows_msvc` environment variable to provide CMake guidance on the compiler setup. We should avoid overriding the configuration it provides.
* Adds a CI job to verify that we can build for the `*_pc_windows_msvc` targets from an Ubuntu host.
=> Allow cmake toolchain env

aws-lc-fips-sys/builder/main.rs
* Windows/FIPS builds invoke `vcvarsall.bat` to acquire the environment variables required for a build.  The environment is parsed from the output of [printenv.bat](https://github.com/aws/aws-lc-rs/blob/main/aws-lc-fips-sys/builder/printenv.bat).
* On some hosts the output of `printenv.bat` can be larger than 4kb. This changes the buffer size to 16k.
* I was having this problem on a local Windows box. The FIPS build would fail, and I could see that the output from `printenv.bat` was being cutoff early.  With this change the build succeeds.
```
> cargo build -p aws-lc-rs --no-default-features --features fips
Compiling cc v1.0.92
Compiling aws-lc-rs v1.7.2 (C:\Users\justi\repos\aws-lc-rs\aws-lc-rs)
Compiling cmake v0.1.50
Compiling aws-lc-fips-sys v0.12.8 …
```
=> vcvarsall.bat can make very large env

aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-fips-sys/builder/main.rs, aws-lc-sys/builder/cmake_builder.rs, aws-lc-sys/builder/main.rs
When using cmake for building, make sure to include the cmake files and parameters that openharmony needs to ensure a successful build.
Point out areas that need special attention or support during the review process. Discuss architecture or design changes.
How is this change tested (unit tests, fuzz tests, etc.)? Are there any testing steps to be verified by the reviewer?
=> feat: support openharmony platform

.github/workflows/pregen-bindings.yml, aws-lc-fips-sys/builder/bindgen.rs, aws-lc-sys/builder/bindgen.rs
* Missing comma in bindings "prelude".
* The "prelude" is only used for the pre-generated bindings, which currently all have the comma.
* Added CI job that exercises the bindings pregeneration logic
=> Missing comma

aws-lc-rs/src/cipher.rs, aws-lc-rs/src/cipher/streaming.rs, aws-lc-rs/src/cipher/tests/fips.rs, aws-lc-rs/src/ptr.rs, aws-lc-rs/tests/cipher_test.rs
* Resolves: #396
* New structs `StreamingEncryptionKey` and `StreamingDecryptionKey` supporting operations with AES128 and AES256 in CTR and CBC (w/ PKCS7 padding) modes
* The `update` and `final` functions return a `BufferUpdate` struct indicating where the provided output buffer was modified.
* Added example to `cipher` module documentation.
* Added tests.
=> Streaming API for CBC and CTR cipher modes

.github/workflows/analysis.yml, aws-lc-rs/Cargo.toml
* Prepare for release v1.8.0
* Added CI test for metadata values.
=> Prepare release v1.8.0

aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-sys/builder/cmake_builder.rs
So sorry that we must update cmake config for openharmony armv7a & x86_64.
Before: 
we will get some errors
Point out areas that need special attention or support during the review process. Discuss architecture or design changes.
How is this change tested (unit tests, fuzz tests, etc.)? Are there any testing steps to be verified by the reviewer?
=> fix(build): armv7a and x86_64's ohos should set asm args

aws-lc-rs/Cargo.toml
* Fix our MSRV CI check due to latest cc changing its MSRV to 1.67.0.
=> Latest cc requires Rust 1.67.0

.github/workflows/cross.yml, aws-lc-fips-sys/builder/main.rs, aws-lc-sys/builder/cmake_builder.rs, aws-lc-sys/builder/main.rs
* Add CI testing for 'i686-pc-windows-msvc' and 'i686-pc-windows-gnu'
* For Windows, set `static_crt` for our build. See: #453 
=> Test more windows targets

aws-lc-sys/builder/bindgen.rs, aws-lc-sys/builder/cc_builder/aarch64_apple_darwin.rs, aws-lc-sys/builder/cc_builder/aarch64_unknown_linux_gnu.rs, aws-lc-sys/builder/cc_builder/aarch64_unknown_linux_musl.rs, aws-lc-sys/builder/cc_builder/i686_unknown_linux_gnu.rs, aws-lc-sys/builder/cc_builder/x86_64_apple_darwin.rs, aws-lc-sys/builder/cc_builder/x86_64_unknown_linux_gnu.rs, aws-lc-sys/builder/cc_builder/x86_64_unknown_linux_musl.rs, aws-lc-sys/src/aarch64_apple_darwin_crypto.rs, aws-lc-sys/src/aarch64_apple_darwin_crypto_ssl.rs, aws-lc-sys/src/aarch64_unknown_linux_gnu_crypto.rs, aws-lc-sys/src/aarch64_unknown_linux_gnu_crypto_ssl.rs, aws-lc-sys/src/aarch64_unknown_linux_musl_crypto.rs, aws-lc-sys/src/aarch64_unknown_linux_musl_crypto_ssl.rs, aws-lc-sys/src/i686_unknown_linux_gnu_crypto.rs, aws-lc-sys/src/i686_unknown_linux_gnu_crypto_ssl.rs, aws-lc-sys/src/x86_64_apple_darwin_crypto.rs, aws-lc-sys/src/x86_64_apple_darwin_crypto_ssl.rs, aws-lc-sys/src/x86_64_unknown_linux_gnu_crypto.rs, aws-lc-sys/src/x86_64_unknown_linux_gnu_crypto_ssl.rs, aws-lc-sys/src/x86_64_unknown_linux_musl_crypto.rs, aws-lc-sys/src/x86_64_unknown_linux_musl_crypto_ssl.rs
* Bindgen was ignoring the `#include "openssl/experimental/kem_deterministic_api.h"` that we added to the "rust_wrapper.h".
* Bindgen's "allowlist pattern" was updated to allow include files in subdirectories.
* Workflow run is here: https://github.com/aws/aws-lc-rs/actions/runs/9975128440
=> Fix bindgen include file allowlist

aws-lc-sys/builder/cmake_builder.rs
=> Improve Android support

aws-lc-rs/src/agreement.rs, aws-lc-rs/src/ed25519.rs, aws-lc-rs/src/rsa/key.rs, book/src/requirements/windows.md
* Update docs for `as_ref` functions of keys to indicate the encoding being used.
* Update User Guide now that Ninja is no longer required for Windows/ARM64 builds.
=> Fill gaps in documentation

.github/workflows/cross.yml, aws-lc-sys/builder/bindgen.rs, aws-lc-sys/builder/main.rs
* Addresses #476
* Add CI test for FreeBSD
=> Add CI test for FreeBSD

aws-lc-rs/Cargo.toml
This seems to be unused, and has the effect of removing several large proc macro dependencies from the dependency tree:
```
--- before	2024-07-29 11:07:47.128726312 +0100
+++ after	2024-07-29 11:08:01.911637253 +0100
@@ -24,15 +24,6 @@
├── paste v1.0.15 (proc-macro)
├── untrusted v0.7.1
└── zeroize v1.8.1
-    └── zeroize_derive v1.4.2 (proc-macro)
-        ├── proc-macro2 v1.0.86
-        │   └── unicode-ident v1.0.12
-        ├── quote v1.0.36
-        │   └── proc-macro2 v1.0.86 (*)
-        └── syn v2.0.72
-            ├── proc-macro2 v1.0.86 (*)
-            ├── quote v1.0.36 (*)
-            └── unicode-ident v1.0.12
```
According to `cargo build --timings` the eliminated dependencies account for 3.95s of the build time, which compares unfavourably with the entire aws-lc-sys build …
=> Drop unused `zeroize_derive` feature dependency

aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-fips-sys/builder/main.rs, aws-lc-sys/builder/cc_builder.rs, aws-lc-sys/builder/cmake_builder.rs, aws-lc-sys/builder/main.rs
* Addresses #470
* Strip the full source paths from "release" artifacts.
=> Trim source paths for release binaries

aws-lc-rs/src/agreement.rs
* Tests for "agreement" were largely using known test values or "KATs". This change adds a test using randomly generated keys.
=> Test agreement with randomly generated keys

aws-lc-rs/src/aead/quic.rs, aws-lc-rs/src/cipher/aes.rs, aws-lc-rs/src/cipher/block.rs, aws-lc-rs/src/cipher/chacha.rs, aws-lc-rs/src/cipher/key.rs
* Avoid unnecessary copy - `Block::from` can consume its argument.
=> Block::from can consume its argument

aws-lc-rs/src/digest/digest_ctx.rs
* The first parameter of `EVP_MD_CTX_copy` should not be initialized
=> First parameter to EVP_MD_CTX_copy should not be initialized

aws-lc-sys/builder/main.rs
Addresses: #484
When external bindgen is used, inspect the version number detected and provide guidance on how to upgrade.
* The output is sent to stderr and is only seen when the build fails.
=> Report bindgen version

aws-lc-sys/builder/cc_builder.rs
Addresses #496
* Provide more clarity when the build fails due to the detection of a compiler bug.
=> Clarify the failure when a compiler bug is detected.

aws-lc-rs/src/aead/aead_ctx.rs, aws-lc-rs/src/agreement.rs, aws-lc-rs/src/bn.rs, aws-lc-rs/src/cipher/streaming.rs, aws-lc-rs/src/ec.rs, aws-lc-rs/src/ec/key_pair.rs, aws-lc-rs/src/ed25519.rs, aws-lc-rs/src/endian.rs, aws-lc-rs/src/evp_pkey.rs, aws-lc-rs/src/kem.rs, aws-lc-rs/src/ptr.rs, aws-lc-rs/src/rand.rs, aws-lc-rs/src/rsa/encoding.rs, aws-lc-rs/src/rsa/encryption/oaep.rs, aws-lc-rs/src/rsa/encryption/pkcs1.rs, aws-lc-rs/src/rsa/key.rs, aws-lc-rs/src/rsa/signature.rs
* Makes acquiring a mutable or const pointer from a `ManagedPointer` explicit (instead of using Deref):
* Adds a `MutPointer` type as an analog of `ConstPointer`.
* On a mutable `ManagedPointer` use `as_mut` to obtain a `MutPointer`. 
* On a shared `ManagedPointer` use `as_const` to obtain a `ConstPointer`.
* On a shared `ManagedPointer` use `as_mut_unsafe` to obtain a `MutPointer`.
The uses of `as_mut_unsafe` are limited to calls made to the following AWS-LC functions:
* EVP_PKEY_CTX_new
* EVP_PKEY_up_ref
* EVP_DigestSignInit
* EVP_DigestVerifyInit
These function only modify `EVP_PKEY` ref-count while holding a global lock.
=> Safer pointer dereferences

.github/workflows/cross.yml, aws-lc-fips-sys/builder/main.rs
* Updates the aws-lc-fips-sys build scrips with some improvements from aws-lc-sys.
* A added a FIPS test to the FreeBSD CI step.
=> Update aws-lc-fips-sys build script

.github/workflows/tests.yml, aws-lc-sys/builder/cc_builder/aarch64_apple_darwin.rs, aws-lc-sys/builder/cc_builder/x86_64_apple_darwin.rs, scripts/build/collect_build_src.sh
On macos, the `collect_build_src.sh` was not identifying `refcount_lock.c` as a source file b/c our automation performs the final build using the (default) C11 standard. However, `refcount_lock.c` is still needed for C99 builds, but it was not listed.
* Updated `collect_build_src.sh` so that it will always include both `refcount_lock.c` and `refcount_c11.c` (although only one of these will actually be useful to any specific build).
* Added CI testing for popular platforms to verify that setting `AWS_LC_SYS_C_STD` to either `99` or `11` results in a successful build.
* Update the `cc_builder` source listing so that `refcount_lock.c` is included.
* I ran the automated workflow and verified that the `cc_builder` source listings it produces match what's in this PR: …
=> Fix for C99; Add tests

aws-lc-rs/Cargo.toml
Bump aws-lc-rs to v1.9.0 in preparation for release.
=> Bump aws-lc-rs to v1.9.0

aws-lc-sys/Cargo.toml
This fixes a downstream build failure:
```
Compiling aws-lc-sys v0.21.0
error[E0308]: mismatched types
--> /home/jbp/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.21.0/builder/cc_builder.rs:128:31
|
128 |                   cc_build.flag(format!(
|  _______________________________^
129 | |                     "-ffile-prefix-map={}=",
130 | |                     self.manifest_dir.display()
131 | |                 ));
| |_________________^ expected `&str`, found `String`
|
= note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)
For more information about this error, try `rustc --explain E0308`.
error: could not compile `aws-lc-sys` (build script) due to 1 previous error
warning: build failed, waiting for other …
```
=> bump cc version to fix build

aws-lc-sys/builder/cmake_builder.rs
* Typo in `check_dependencies` is preventing the intended error message from being displayed. When NASM is not present, the build proceeds directly into the (doomed to fail) CMake build.  
* This bug affects the error messaging on a failed build, but not the "success" nor the "correctness" of that build. (The `use_prebuilt_nasm()` function is working as intended.)
=> Fix typo: x86_64

.github/workflows/analysis.yml, .github/workflows/cross.yml, aws-lc-sys/builder/cc_builder.rs
Older GCC compilers do not support the `-ffile-prefix-map` option.
Check whether `-ffile-prefix-map` is supported before use.  Fallback to using `-fdebug-prefix-map` if not.
=> Fix for older GCC < 8.1.0

.github/workflows/analysis.yml, aws-lc-rs/src/agreement.rs, aws-lc-rs/src/agreement/ephemeral.rs, aws-lc-sys/builder/cc_builder.rs, aws-lc-sys/builder/cmake_builder.rs
* Consumers using older GCC compilers (< v8.1) with the `AWS_LC_SYS_CMAKE_BUILDER=1` environment variable set experience build failures due to GCC lacking support for the `-ffile-prefix-map=` option.
* For x86 (32-bit) builds, older GCC compilers do not assume the availability of SSE2. However, SSE2 is required by AWS-LC assembly.
* Comment out the use of `-ffile-prefix-map=` for the CMake builder until we have a better solution.
* Sets the `-msse2` compiler option on `x86` builds that use the "cc" builder.
=> Revert `-ffile-prefix-map` usage w/ CMake

.github/workflows/cross.yml
The latest production release of FreeBSD is 14.1
Resolves #535
Update from 13.2 to 14.1
Check that the cross.yaml build works for FreeBSD.
=> Update FreeBSD version to 14.1 in cross compiling workflow

.github/workflows/tests.yml, aws-lc-sys/builder/cc_builder.rs, aws-lc-sys/builder/cmake_builder.rs, aws-lc-sys/builder/main.rs
The "CMake builder" now defers to the "CC builder" logic to determine which flags are appropriate for the compiler in the build environment. (Restores the usage of `-ffile-prefix-map` compiler option with CMake build, which had been [disabled in a previous PR](https://github.com/aws/aws-lc-rs/pull/526).)
<details>
<summary>Tested with GCC 7.2</summary>
```
❯ cc --version
cc (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
...
❯ AWS_LC_SYS_CMAKE_BUILDER=1 cargo test -p aws-lc-sys --release
...
test result: ok. 95 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running tests/sanity-tests.rs …
```
=> Improve consistency between CC and CMake builds

scripts/build/collect_symbols.sh, scripts/generate/_collect_symbols_build.sh
To land https://github.com/aws/aws-lc/pull/1877, must filter new s2n-bignum symbols that are not supposed to have external linkage. Similar to e.g. https://github.com/aws/aws-lc-rs/pull/286
=> Filter s2n-bignum symbols with prefix p256_montjscalarmul

docker/build_images.sh, docker/ubuntu-18.04/Dockerfile
Add an Ubuntu 18.04 docker image for testing older GCC (e.g. v4.8, v5 & v6).
=> Add Ubuntu 18.04 image for testing older GCC

.github/workflows/analysis.yml, .github/workflows/cross.yml, .github/workflows/fips-bindings-generator.yml, .github/workflows/fips.yml, .github/workflows/integration.yml, .github/workflows/pregen-bindings.yml, .github/workflows/sys-bindings-generator.yml, .github/workflows/tests.yml
* Update CI to use more recent MacOS images.
* Support for MacOS 12 ended September 16, 2024: https://en.wikipedia.org/wiki/MacOS_Monterey
* Ninja only needed for Windows/FIPS and `cargo-xwin` builds.  Not installing it unless needed.
=> Update CI runners for MacOS

.github/workflows/cross.yml
Fix typo in the cross build for FreeBSD. Only the latest release was being targeted.
=> Fix FreeBSD build not targetting release 13.4

aws-lc-rs/src/kem.rs, aws-lc-rs/src/unstable/kdf.rs, aws-lc-rs/src/unstable/kem.rs
Resolves #ISSUE-NUMBER1
Addresses #ISSUE-NUMBER2
Describe current behavior and how your code changes that behavior. If there are no issues this pr is resolving, explain why this change is necessary.
Point out areas that need special attention or support during the review process. Discuss architecture or design changes.
How is this change tested (unit tests, fuzz tests, etc.)? Are there any testing steps to be verified by the reviewer?
=> Add ML-KEM 512, 768, and 1024

.github/workflows/tests.yml, aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-sys/builder/cc_builder.rs
* The use of `-ffile-prefix-map` within the aws-lc-fips-sys build scripts was causing build failures with older compilers. This change conditions the use of the flag on the detection of compiler support.
* For the FIPS build most, but not all, of the build environment source paths are being removed. Changes to the AWS-LC CMake scripts are likely needed to fully support this.
* Added a CI dimension to test older compilers with FIPS feature enabled.
=> Support FIPS feature w/ old compilers

aws-lc-sys/builder/cmake_builder.rs
Addresses #562
Improvement to Android build:
* Defer the setting of `CMAKE_SYSTEM_NAME` and `CMAKE_SYSTEM_PROCESSOR` to cmake-rs.
* Log relevant environment variables to help with diagnosis and debugging.
=> Improve handling/logging for Android builds

.github/workflows/tests.yml
* Enable C11 std test for windows
=> Enable C-std (C11) test for windows

aws-lc-rs-testing/benches/kem_benchmark.rs, aws-lc-rs/src/cipher.rs, aws-lc-rs/src/cipher/streaming.rs, aws-lc-rs/src/test.rs
Resolves #575
Adds support for AES cipher feedback 128-bit mode (CFB-128). I was going to also support CFB 1-bit and CFB 8-bit modes but have a smaller concern around being able to support that with the fips feature enabled currently. Need to investigate that further, so we may come back at a later date and add support for those additional bit-mode variants. For now this resolves the requester's needs.
=> Support for AES CFB (128-bit) mode

aws-lc-rs/src/ed25519.rs
Resolves #572 
Adds support for `Ed25519KeyPair::generate()`. I've opted to not allow passing a reference to an `rng` like that presented in the issue, as the parameter would be ignored like it is in the other generation functions available today.
=> Add support for Ed25519KeyPair::generate

aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-rs/src/aead/tests/fips.rs, aws-lc-rs/src/aead/tests/fips/chacha20_poly1305_openssh.rs, aws-lc-rs/src/ed25519.rs, aws-lc-rs/src/test.rs
* Our MacOS (x86-64) builds for `aws-lc-sys-fips` have started failing recently. For example: https://github.com/aws/aws-lc-rs/actions/runs/11675784224/job/32547525030#step:9:1
```
clang: error: overriding '-mmacosx-version-min=13.7' option with '--target=x86_64-apple-macosx14.2' [-Werror,-Woverriding-t-option]
```
* This issue only affects our FIPS build due to [platform-specific CMake logic](https://github.com/aws/aws-lc/blob/49215e8da6bed791655fbbbd8c6b8850c8e687a2/crypto/fipsmodule/CMakeLists.txt#L498) that adds the `-mmacosx-version-min=` compiler flag on FIPS builds. 
* This change adds the `-Wno-overriding-t-option` compiler flag when building `aws-lc-sys-fips` to avoid this failure.
* Fixed several new Clippy findings affecting test logic.
By submitting this pull request, I …
=> Disable `-Woverriding-t-option`

aws-lc-sys/builder/cmake_builder.rs
I found that [this error](https://github.com/aws/aws-lc-rs/actions/runs/11862568768/job/33062282018?pr=588#step:4:250) can also happen in aws-lc-sys:
```
error: failed to run custom build command for `aws-lc-sys v0.23.0 (/Users/runner/work/aws-lc-rs/aws-lc-rs/aws-lc-sys)`
...
clang: error: overriding '-mmacosx-version-min=13.7' option with '--target=x86_64-apple-macosx14.2' [-Werror,-Woverriding-t-option]
```
=> Also aws-lc-sys -Wno-overriding-t-option

aws-lc-rs/src/aead/quic.rs, aws-lc-rs/src/cipher.rs, aws-lc-rs/src/cipher/aes.rs, aws-lc-rs/src/cipher/block.rs, aws-lc-rs/src/cipher/key.rs, aws-lc-rs/src/cipher/padded.rs, aws-lc-rs/src/cipher/streaming.rs, aws-lc-rs/tests/cipher_test.rs
Resolves #573
* Adds support for ECB mode with pkcs7 padding
* Adds support for ECB mode with pkcs7 padding using the streaming interface
* Adds support for ECB mode without padding (requires input/output to be multiple of block length).
* Streaming mode doesn't support ECB without padding as the EVP interface doesn't have a way to toggle off the behavior for this mode.
=> AES ECB mode support

aws-lc-fips-sys/builder/main.rs, aws-lc-rs/src/cipher.rs, aws-lc-rs/src/cipher/padded.rs, aws-lc-sys/builder/cc_builder.rs, aws-lc-sys/builder/main.rs
* Fix latest clippy lints.
* Fix rustfmt
=> Fix latest clippy lints

aws-lc-fips-sys/builder/cmake_builder.rs
Addresses:
* #600
* The documentation build for [aws-lc-fips-sys on docs.rs](https://docs.rs/crate/aws-lc-fips-sys) is failing.  The build log indicates that it's due to the Go compiler being unable to initialize its cache directory: https://docs.rs/crate/aws-lc-fips-sys/0.12.14/builds/1543179
```
...
[INFO] [stderr]   --- stderr
[INFO] [stderr]   failed to initialize build cache at /.cache/go-build: mkdir /.cache: permission denied
...
```
* The [`GOCACHE` environment variable](https://pkg.go.dev/cmd/go#hdr-Environment_variables) determines the location for this directory.
* Sets the GOCACHE environment variable to be beneath ${OUT_DIR}, in which the Go compiler should have permission to create its `.cache` directory.
By submitting this pull request, I confirm that my contribution is …
=> Set GOCACHE under OUT_DIR

aws-lc-sys/builder/cc_builder.rs, aws-lc-sys/builder/cmake_builder.rs
Addresses:
* #602
* Use of the `-Wno-overriding-t-option` causes build failure on certain platforms. Limit its use to the specific environments that it might be needed.
=> Fix for aarch64-apple-ios

aws-lc-rs/src/rsa/encryption.rs, aws-lc-rs/src/rsa/key.rs, aws-lc-rs/tests/basic_rsa_test.rs
Resolves #581 
Adds `impl TryInto<PublicEncryptingKey> for PublicKeyComponents`.
N/A
Im not sure how to implement unit tests for this change would need a reviewer to assist with this. I tested them in my personal application and they functioned as expected.
=> Implement TryInto<PublicEncryptingKey> for PublicKeyComponents

.github/workflows/compilers.yml, .github/workflows/tests.yml, aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-sys/builder/cc_builder.rs, aws-lc-sys/builder/cmake_builder.rs
* #599
* aws/aws-lc#2005
* Fix handling of spaces in the source/build paths.
* Revert recent MSRV violations
* Moved several compiler-version tests to its own workflow.
New tests added.
=> Handle spaces in source/build paths

aws-lc-rs/src/aead.rs, aws-lc-rs/tests/aead_test.rs
Addresses #570
Provides the ability for a user to precompute the next operation's nonce value for `OpeningKey` and `SealingKey` types via `OpeningKey::prepare_operation` and `SealingKey::prepare_operation` which return `OpeningKeyOpMut` and `SealingKeyOpMut` respectively containing the nonce for the encapsulated operation. Each type provides a `nonce()` method by which the nonce can be retrieved by the caller prior to invoking each types respective opening and sealing operation which will use the nonce.
=> Add ability to prepare the next operation and it's associated nonce for OpeningKey and SealingKey

.github/workflows/cross.yml, .github/workflows/tests.yml, aws-lc-sys/builder/main.rs
Addresses #620
* Fix external bindgen for `i686-pc-windows-gnu`
* Add/Fix CI tests for various Windows targets
=> Fix i686-pc-windows-gnu external bindgen

aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-fips-sys/builder/main.rs, aws-lc-rs/Cargo.toml
Addresses #569
Provide warning to consumers when using an unsupported compiler for the FIPS build.
N/A
Manually tested on MacOS, Ubuntu and Windows.
=> Warn unsupported compiler on FIPS build

aws-lc-sys/builder/main.rs
Addresses #624
Improve error handling when invocation of `bindgen-cli` fails.
=> Improve bindgen-cli error handling

aws-lc-rs/scripts/run-s2n-quic-integration.sh
* Fix for the s2n-quic integration test.
=> Fix s2n-quic integ test

scripts/build/collect_symbols.sh, scripts/generate/_collect_symbols_build.sh
* Filter our symbols recently added to s2n-bignum.
* I tested this using our bindings generation workflow w/ the latest commit on main: https://github.com/aws/aws-lc-rs/actions/runs/12433917705
=> Add new s2n-bignum symbols to filter

aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-sys/builder/cmake_builder.rs
Related to https://github.com/aws/aws-lc-rs/issues/571#issuecomment-2453515258
The build script for aws-lc-sys appends a library search path to the final linker command line. On Windows environments when building with lld-link.exe, the inclusion of an empty directory at the end of this path can cause a build failure.
The problematic path looks like this: `/LIBPATH:C:\\\\a\\\\servo\\\\servo\\\\target\\release\\build\\aws-lc-sys-d847be10163c7448\\out\\build\\artifacts\\`
The presence of the `\\` at the end of the path causes the subsequent character to be treated as an escaped character, leading to a failure to parse the linker argument that follows this.
Since the final component of the path is always empty, we can remove it without any behaviour change.
Verified this change by building …
=> Avoid appending empty path to artifact directory.

.github/workflows/analysis.yml, .github/workflows/fips-bindings-generator.yml, .github/workflows/pregen-bindings.yml, .github/workflows/sys-bindings-generator.yml, aws-lc-rs/util/process-criterion-csv.rs, scripts/tools/cargo-dig.rs, scripts/tools/semver.rs, scripts/tools/target-platform.rs
There is no need to still tie our Rust scripts to the `nightly-2024-05-22` toolchain.
* Verified bindgen workflow still succeeds with this commit: https://github.com/aws/aws-lc-rs/actions/runs/12437445624
=> Update nightly toolchain used for -Zscript

aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/builder/main.rs, aws-lc-fips-sys/builder/sys_bindgen.rs, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc, aws-lc-fips-sys/src/aarch64_apple_darwin_crypto.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_gnu_crypto.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_musl_crypto.rs, aws-lc-fips-sys/src/x86_64_apple_darwin_crypto.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_gnu_crypto.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_musl_crypto.rs
* Made change to "allowlist" for headers so that `openssl/experimental/kem_deterministic_api.h` can be picked up.
* Improve logic around use of external bindgen (i.e., `bindgen-cli`).
* Bump version of aws-lc-fips-sys to v0.13.1.
* Only [first](https://github.com/aws/aws-lc-rs/pull/651/commits/4acaff19b530314f0bc533597516474acc098608) commits has manual changes.
* See automated workflow here: https://github.com/aws/aws-lc-rs/actions/runs/12671943594
=> Prepare aws-lc-fips-sys v0.13.1

aws-lc-fips-sys/CMakeLists.txt, aws-lc-sys/CMakeLists.txt, aws-lc-sys/builder/cc_builder.rs, aws-lc-sys/builder/main.rs
Improve messaging when a contributor clones our repo but doesn't initialize the submodules prior to a build.
=> Improve message when repo submods not initialized

aws-lc-rs/src/ec.rs, aws-lc-rs/src/ec/key_pair.rs, aws-lc-rs/src/ec/signature.rs, aws-lc-rs/src/signature.rs
* Migrate ECDSA structs/functions into `ec::signature` module.
No changes to API detected.
```
❯ cargo public-api diff latest
...
Removed items from the public API
=================================
(none)
Changed items in the public API
===============================
(none)
Added items to the public API
=============================
(none)
```
=> Refactor ECDSA structs into ec::signature

aws-lc-rs/src/rand.rs, aws-lc-rs/src/signature.rs
* Update Ed25519 doc-test to use the "generate()` function for key generation instead of `generate_pkcs8v1()`.
* Increase the number of "random" values collected so that mean and variance should always remain within the asserted bounds.
=> Improve Ed25519 doctest; improve rand test

.github/workflows/cross.yml, aws-lc-fips-sys/builder/cmake_builder.rs
Addresses #655
Fix fips build for certain CPU targets that lack assembly optimized implementations.
Updated CI.
=> Fix fips build for s390x

.github/workflows/fips.yml, aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-fips-sys/builder/main.rs, aws-lc-fips-sys/src/lib.rs, aws-lc-rs/src/lib.rs, scripts/tests/assert_cpu_jitter_entropy.rs
Addresses: CryptoAlg-2814
* Detects environment variable `AWS_LC_FIPS_SYS_CPU_JITTER_ENTROPY` indicating that AWS-LC should be built to use cpu jitter entropy.
* Adds functions to allow consumers to verify cpu jitter entropy is in use at runtime.
* The required `FIPS_is_entropy_cpu_jitter` function is not yet available on the FIPS branch.  So the check currently only verifies that the "cpu_jitter_entropy" configuration was successfully detected by the build scripts.
* This PR depends on: #649
* Added script/CI that verifies that the `fips_cpu_jitter_entropy()` assertion succeeds.
=> Support FIPS build w/ CPU Jitter

.github/docker_images/ohos-5.0.0/Dockerfile, .github/docker_images/ohos-5.0.0/aws_lc_rs_build.sh, .github/docker_images/ohos-5.0.0/build_image.sh, .github/docker_images/ohos-5.0.0/entry.sh, .github/workflows/cross.yml, aws-lc-sys/builder/cc_builder.rs, aws-lc-sys/builder/cmake_builder.rs, aws-lc-sys/builder/main.rs
Addresses #648 
* Only collect cflags from `cc` when a cmake toolchain is not provided.
* Add a few necessary tweaks when using the Open Harmony CMake toolchain.
* Added Docker Image that installs the OpenHarmony SDK.
* Added CI job that tests building for targets `aarch64-unknown-linux-ohos`, `armv7-unknown-linux-ohos`, and `x86_64-unknown-linux-ohos`.
=> Fix build for Open Harmony

aws-lc-rs/src/ed25519.rs, aws-lc-rs/tests/ed25519_tests.rs
Resolves #662
`Ed25519KeyPair` currently cannot be constructed from a raw private key seed. This copies the `ring` `from_seed_unchecked` API which makes it possible to do so.
I've moved most of the `from_seed_and_public_key` implementation to `from_seed_unchecked` and had `from_seed_and_public_key` call it. I'm not sure if it's ok for `from_seed_and_public_key` to do more work before rejecting the seed, in case the provided public key doesn't match the one derived from the seed.
I've added a test for the new function together with the pre-existing test for `from_seed_and_public_key`. I've also tested my application and confirmed the `from_seed_unchecked` API works the same as the `from_seed_unchecked` unchecked function from `ring`.
By submitting this pull request, I confirm that my …
=> Implement `from_seed_unchecked` for `Ed25519KeyPair`

aws-lc-rs/Cargo.toml
* Prepare `v1.12.2`.
* We need to bump the `aws-lc-fips-sys` dependency to `v0.13.1` b/c we use a newly added function.
=> Prepare v1.12.2

aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc, aws-lc-fips-sys/src/aarch64_apple_darwin_crypto.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_gnu_crypto.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_musl_crypto.rs, aws-lc-fips-sys/src/x86_64_apple_darwin_crypto.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_gnu_crypto.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_musl_crypto.rs
Addresses P189559642
* Update aws-lc-fips-sys to v0.13.2.
* Use the latest commit on AWS-LC's fips-2024-09-27 branch
* Only manual change is first commit: https://github.com/aws/aws-lc-rs/commit/09a336142fd4c6f30f5f49dad52a24530e52d2be
* Automated workflow is here: https://github.com/aws/aws-lc-rs/actions/runs/12909061549
=> Prepare aws-lc-fips-sys v0.13.2

.github/docker_images/alpine-3.20/Dockerfile, .github/docker_images/alpine-3.20/aws_lc_rs_build.sh, .github/docker_images/alpine-3.20/build_image.sh, .github/docker_images/alpine-3.20/entry.sh, .github/workflows/cross.yml, aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-rs/Makefile, aws-lc-rs/src/agreement.rs, aws-lc-rs/src/cbb.rs, aws-lc-rs/src/digest/digest_ctx.rs, aws-lc-rs/src/hkdf.rs, aws-lc-rs/src/hmac.rs, aws-lc-rs/src/key_wrap.rs, aws-lc-rs/src/rsa/encryption.rs, aws-lc-rs/src/rsa/encryption/oaep.rs, aws-lc-rs/src/rsa/encryption/pkcs1.rs, aws-lc-rs/src/rsa/key.rs, aws-lc-rs/src/rsa/signature.rs, aws-lc-rs/tests/aead_test.rs, aws-lc-rs/tests/ecdsa_tests.rs, aws-lc-rs/tests/ed25519_tests.rs, aws-lc-rs/tests/rsa_test.rs, aws-lc-sys/builder/cc_builder.rs, aws-lc-sys/builder/cmake_builder.rs, aws-lc-sys/builder/main.rs, docker/alpine-3.20/Dockerfile, docker/build_images.sh
Addresses: #658
* Build scripts now map the `???-alpine-linux-musl` targets to the `???-unknown-linux-musl` targets that we support.
* Adds CI and docker image for testing builds on Alpine Linux.
CI Job added,
=> Improve support for alpine linux

aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-fips-sys/builder/main.rs, aws-lc-sys/builder/cc_builder.rs
Some users experiencing build failures relating to the following error:
```
clang: error: overriding '-mmacosx-version-min=14.7' option with '--target=arm64-apple-macosx15.1' [-Werror,-Woverriding-option]
make[2]: *** [aws-lc/crypto/fipsmodule/CMakeFiles/bcm_library.dir/bcm.c.o] Error 1
```
* This change applies the same fix for `-Woverriding-option` as we had done for `-Woverriding-t-option`.
N/A
A user experiencing this problem confirmed this change resolved it.
=> Avoid fips MacOS failure due to -Woverriding-option

aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-rs/src/ec/key_pair.rs, aws-lc-rs/src/evp_pkey.rs
* [`EcdsaKeyPair::from_private_key_der`](https://docs.rs/aws-lc-rs/latest/aws_lc_rs/signature/struct.EcdsaKeyPair.html#method.from_private_key_der) should accept either RFC 5208 or RFC 5915 encodings.
* I found this problem while investigating the [failure of our rustls integ tests](https://github.com/aws/aws-lc-rs/actions/runs/13116980204/job/36595945901?pr=678#step:6:827).
* Added a test to prevent future regression.
* I verified that this fixes the test failure in rcgen.
=> Fix regression in EcdsaKeyPair::from_private_key_der

aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc, aws-lc-fips-sys/src/aarch64_apple_darwin_crypto.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_gnu_crypto.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_musl_crypto.rs, aws-lc-fips-sys/src/x86_64_apple_darwin_crypto.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_gnu_crypto.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_musl_crypto.rs, aws-lc-rs/src/evp_pkey.rs
* Bumps the `aws-lc-fips-sys` version number to v0.13.3
=> Prepare aws-lc-fips-sys v0.13.3

aws-lc-rs/src/agreement.rs, aws-lc-rs/src/bn.rs, aws-lc-rs/src/ec.rs, aws-lc-rs/src/ec/key_pair.rs, aws-lc-rs/src/ec/signature.rs, aws-lc-rs/src/ed25519.rs, aws-lc-rs/src/evp_pkey.rs, aws-lc-rs/src/kem.rs, aws-lc-rs/src/lib.rs, aws-lc-rs/src/pq.rs, aws-lc-rs/src/rsa/encryption.rs, aws-lc-rs/src/rsa/key.rs, aws-lc-rs/src/rsa/signature.rs, aws-lc-rs/src/rsa/tests/fips.rs, aws-lc-rs/tests/rsa_test.rs
* Consolidates various places we call `EVP_PKEY_keygen`
* Consolidates various placeswe call `EVP_DigestSign` and `EVP_DigestVerify`.
* Start of implementation for ML-DSA
* RSA key generation will now use `EVP_PKEY_keygen`.  When the "fips" feature is enabled, the FIPS-approved key generation mechanism will be used for all RSA keys.
* RSA "fips" tests had slight modification due to change mentioned above.
=> EVP_PKEY refactoring for keygen/sign/verify; Start of ML-DSA impl

aws-lc-rs/src/rsa/key.rs
Addresses #697
Add conversion from `&PublicKey` to `PublicKeyComponents<&[u8]>`. Seems pretty straightforward?
(I looked at the minor issue as well, but I'm not sure how to compute the correct `public_modulus_len()` from the decomposed `modulus`.)
No tests yet -- let me know if/where I should add some test coverage.
=> Implement From<&PublicKey> for PublicKeyComponents

aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-sys/builder/cmake_builder.rs
Addresses #691
Improve handling of size-optimized builds, specifically, [opt-levels "s" and "z"](https://doc.rust-lang.org/cargo/reference/profiles.html#opt-level).
=> Build script handling of OPT_LEVEL='s'

Cargo.toml
Exclude Rust scripts from workspace to avoid failure.
=> Exclude Rust scripts from workspace

aws-lc-rs/Cargo.toml, aws-lc-rs/src/agreement.rs, aws-lc-rs/src/key_wrap.rs
* Recent refactoring dropped support for parsing PKCS8 from `agreement::PrivateKey::from_private_key_der`.  This PR restores that support.
* Bump version to 1.12.5
* We had no function to serialize an ECDH private key to PKCS8. In order to test this, this functionality needed to be added.
* Updated test.
=> Support PKCS8 in agreement::PrivateKey::from_private_key_der

.github/workflows/compilers.yml, aws-lc-rs/src/agreement.rs, aws-lc-sys/builder/cc_builder.rs, aws-lc-sys/builder/main.rs
* GH has deprecated their ubuntu-20.04 runner images.
* This change migrates the jobs to run on an Ubuntu 20.04 docker image running on Ubuntu 22.04.
=> Run compiler tests on ubuntu-22.04

aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/src/lib.rs, aws-lc-rs/Cargo.toml, aws-lc-rs/src/aead.rs, aws-lc-rs/src/encoding.rs, aws-lc-rs/src/kem.rs, aws-lc-sys/Cargo.toml, aws-lc-sys/src/lib.rs
Addresses #722 
* Removes use of paste from all non-test code.
* paste is only used for test generation.
=> No paste dependency

.github/docker_images/cmake_build_versions/Dockerfile, .github/docker_images/cmake_build_versions/aws_lc_rs_build.sh, .github/docker_images/cmake_build_versions/cmake_build.sh, .github/docker_images/cmake_build_versions/entry.sh, .github/workflows/cmake.yml, .github/workflows/integration.yml, .gitmodules, aws-lc-fips-sys/CMakeLists.txt, aws-lc-rs/scripts/run-windows-debug-crt-static-test.sh, aws-lc-sys/CMakeLists.txt, aws-lc-sys/builder/cc_builder.rs, aws-lc-sys/builder/cmake_builder.rs
Addresses:
* #707
* #710
* #716 
* Previously we "harvested" the compiler options used by `cc` to populate `CFLAGS`.  This is unnecessary, as it's [also done by cmake-rs](https://github.com/rust-lang/cmake-rs/blob/master/src/lib.rs#L728-L734). This change identifies any supplementary compiler options as `BuildOption` values. These can be applied to either a `cc` or `cmake` build.
* [cmake-rs strips optimization and debug options](https://github.com/rust-lang/cmake-rs/blob/master/src/lib.rs#L716-L736) out of the CFLAGS environment variable.  This can cause build failure when the build environment produces warnings due to lack of these optimizations.
* Aligning with [the change made in AWS-LC](https://github.com/aws/aws-lc/pull/2219), we're also bumping our CMake minimum version for v3.5.
* …
=> Improve handling of CFLAGS

aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc, aws-lc-fips-sys/src/aarch64_apple_darwin_crypto.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_gnu_crypto.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_musl_crypto.rs, aws-lc-fips-sys/src/x86_64_apple_darwin_crypto.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_gnu_crypto.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_musl_crypto.rs
* Bump `aws-lc-fips-sys` to v0.13.4
* This is needed to publish a version that does not depend on "paste".
* The dependency on "paste" was removed in a previous PR: https://github.com/aws/aws-lc-rs/pull/724
* Manual changes in this commit: https://github.com/aws/aws-lc-rs/commit/0b0ced7b384f25ac0dc4183e00d8e0162bbf495b
* Automated Workflow: https://github.com/aws/aws-lc-rs/actions/runs/13820709450
=> Bump aws-lc-fips-sys to v0.13.4

scripts/tests/test-bindings-pregen.sh
A test script for performing the bindings pregeneration. Useful for when bindings pregeneration is failing.
=> Test script for bindings pregeneration

aws-lc-fips-sys/CMakeLists.txt, aws-lc-sys/CMakeLists.txt
Fix submodule warning that displays on failed CMake build
```
aws-lc-rs on  main via 🦀 v1.85.0
at 15:33:13 ❯ cargo clean && AWS_LC_SYS_CMAKE_BUILDER=1 cargo -vv build -p aws-lc-sys 2>&1 | grep 'MISSING GIT SUBMODULE'
Removed 0 files
[aws-lc-sys 0.27.0]   ###### WARNING: MISSING GIT SUBMODULE ###### Did you initialize the repo's
aws-lc-rs on  main via 🦀 v1.85.0 took 11s
at 15:33:30 ❯ git checkout fix-cmake-submod-warning
Switched to branch 'fix-cmake-submod-warning'
aws-lc-rs on  fix-cmake-submod-warning via 🦀 v1.85.0
at 15:33:41 ❯ cargo clean && AWS_LC_SYS_CMAKE_BUILDER=1 cargo -vv build -p aws-lc-sys 2>&1 | grep 'MISSING GIT SUBMODULE'
Removed 1032 files, 107.1MiB total
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Fix CMake submodule warning

.github/workflows/cross.yml
There's a bug in the clang "atomic" header that's causing the libssl build to fail for `arm-linux-androideabi`:
* It was reported here: https://reviews.llvm.org/D75183
* It was finally fixed here: https://reviews.llvm.org/D118391
* Don't test building libssl on `arm-linux-androideabi`.
* I considered "hacking" around this, but that introduces an unnecessary risk.
* Once cross-rs updates the image for `arm-linux-androideabi` we could re-enable this test.
=> No libssl cross test for arm-linux-androideabi

aws-lc-rs/Cargo.toml, aws-lc-rs/Makefile, aws-lc-rs/src/rsa/encoding.rs, aws-lc-rs/src/rsa/key.rs, aws-lc-rs/tests/rsa_test.rs
Addresses #741
* Support `RsaSubjectPublicKey` serialization to/from X509
* Bump the patch version to 1.12.7.
Added test coverage for new functions.
=> Support RsaSubjectPublicKey to/from X509; Bump version

aws-lc-sys/builder/cc_builder.rs
Change build script to only produce a single library for linking.
=> aws-lc-sys: output only one library

.github/workflows/cross.yml
I don't have the expertise to actually chase this down, but wanted to point out the current issue with trying to build for illumos. This issue is a blocker for upgrading `rustls` package in `atuin` and to move away from `ring`.
---
=> Try to support illumos

.github/workflows/tests.yml, aws-lc-sys/Cargo.toml, aws-lc-sys/builder/cmake_builder.rs, aws-lc-sys/builder/main.rs
* #752
* #753
* Include `err_data_generate.go` and `prebuilt-nasm.sh` in the `aws-lc-sys` crate
* Add support for `AWS_LC_SYS_NO_PREGENERATED_SRC` environment variable that will prevent any pregenerated code from being used.
=> Include Go source in `aws-lc-sys` crate

.github/docker_images/cmake_build_versions/aws_lc_rs_build.sh, .github/workflows/tests.yml, aws-lc-rs/Cargo.toml
* ~~#747~~
* ~~#754~~
* ~~#757~~
* ~~#760~~
* Bump aws-lc-rs to v1.13.0
* Test CMake 4.0 w/ aws-lc-fips-sys build
* Fix Clang 19 test
=> Bump to aws-lc-rs v1.13.0

aws-lc-fips-sys/builder/main.rs, aws-lc-fips-sys/builder/sys_bindgen.rs, aws-lc-sys/builder/main.rs
Resolves #776 
Resolves #777 
This MR modifies `AWS_LC_SYS_INCLUDES` and `AWS_LC_FIPS_SYS_INCLUDES` to use separators corresponding to the OS convention. This is already implemented by Rust's `std::env::split_paths` which is 1:1 with the existing mapping logic.
Additionally, I've added detection of Bindgen's configuration environment variables (in particular  `BINDGEN_EXTRA_CLANG_ARGS`) by using their `CargoCallbacks` class (documentation [here](https://docs.rs/bindgen/latest/bindgen/struct.CargoCallbacks.html)).
-  The change in separation logic for `AWS_LC_SYS_INCLUDES` and `AWS_LC_FIPS_SYS_INCLUDES`
I'm submitting this as draft because I need to test this on GStreamer's gst-plugins-rs repo with a crate override first.
By submitting this pull request, I confirm that my contribution is …
=> Assorted fixes for Windows compilation

.github/workflows/compilers.yml, .github/workflows/cross.yml, .github/workflows/fips.yml, .github/workflows/integration.yml, .github/workflows/tests.yml, aws-lc-fips-sys/builder/cmake_builder.rs, aws-lc-sys/builder/cc_builder.rs, aws-lc-sys/builder/cmake_builder.rs, aws-lc-sys/builder/main.rs
Addresses:
* #765 
* #764 
* Improvements/fixes for how a few CI tests were setting up environment variables.
* Fix MacOS FIPS build for CMake 4.0.
* Support, and give preference to, target-specific environment variables. 
* Support an `AWS_LC_SYS_EFFECTIVE_TARGET` environment variable.
=> Cleanup environment variable usage

Makefile, aws-lc-fips-sys/Cargo.toml, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_asm.h, aws-lc-fips-sys/generated-include/openssl/boringssl_prefix_symbols_nasm.inc, aws-lc-fips-sys/src/aarch64_apple_darwin_crypto.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_gnu_crypto.rs, aws-lc-fips-sys/src/aarch64_unknown_linux_musl_crypto.rs, aws-lc-fips-sys/src/x86_64_apple_darwin_crypto.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_gnu_crypto.rs, aws-lc-fips-sys/src/x86_64_unknown_linux_musl_crypto.rs
* Addresses: #764
* Bump aws-lc-fips-sys to v0.13.6
* Align aws-lc-fips-sys with: https://github.com/aws/aws-lc/commit/bf956839f77f4b3ac3ad637a0b3752be8a3a72f9
* Update Makefile for updating aws-lc-fips-sys
* Manual commit: https://github.com/aws/aws-lc-rs/commit/91b11485e80ea08adfd45e05d894a75816122a32
* Workflow: https://github.com/aws/aws-lc-rs/actions/runs/14623655235
=> Bump aws-lc-fips-sys to v0.13.6

aws-lc-sys/builder/cc_builder.rs
https://github.com/aws/aws-lc/pull/2324 implements a new import method for s2n-bignum upstream in AWS-LC. Among other things it introduces a new folder structure. This messes with assumptions for the aws-lc-rs prefix build, when not using cmake. aws-lc-rs has hard assumptions on the folder structure to add the correct include search paths.
Now s2n-bignum source in upstream AWS-LC is located under `third_party/s2n-bignum/s2n-bignum-imported`. Note `third_party/s2-bignum` contains the AWS-LC-specific header files. Hence we keep the existing search path.
This part of the prefix build of aws-lc-rs is quite brittle. But I can't really come up with any ideas that would resolve that easily.
Tested locally using https://github.com/aws/aws-lc/blob/main/.github/workflows/aws-lc-rs.yml:
* First …
=> Add new include search path folder for no-cmake build because of upstream AWS-LC change #2324

aws-lc-rs/src/signature.rs, aws-lc-rs/tests/ecdsa_tests.rs
Resolves #788 
Implement the `AsRef<[u8]>` trait for the UnparsedPublicKey type to get access to the raw key. 
=> Implement `AsRef<[u8]>` for `UnparsedPublicKey`

scripts/build/collect_build_src.sh
Recent [commit upstream](https://github.com/aws/aws-lc/pull/2324) changed the directory that the s2n-bignum source files are located.
* Due to factors unique to ARM64 macOS, the debug information in the binary points to post-processed s2n-bignum source files in the build directory instead of their original location. The script was making a bad assumption as to the original location of the s2n-bignum source files.
* The "aws-lc-rs" CI integration test for AWS-LC will continue to fail until this is merged.
* I updated my local workspace to align with the latest aws-lc commit on main. I then ran the `test-bindgen-pregen.sh` script to verify that it succeeds against the latest commit.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Update for s2n-bignum-imported

.github/workflows/analysis.yml, .github/workflows/compilers.yml, .github/workflows/cross.yml, .github/workflows/fips-bindings-generator.yml, .github/workflows/fips.yml, .github/workflows/integration.yml, .github/workflows/sys-bindings-generator.yml, .github/workflows/tests.yml
Update macOS GH runners.
The following runner information can be found [here](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).
| Virtual Machine | Processor (CPU) | Memory (RAM) | Storage (SSD) | Architecture | Workflow label |
|-----------------|----------------|--------------|--------------|--------------|----------------|
| macOS | 4 | 14 GB | 14 GB | Intel | macos-13 |
| macOS | 3 (M1) | 7 GB | 14 GB | arm64 | macos-latest, macos-14, macos-15 |
=> Update MacOS GH runners

aws-lc-rs/scripts/run-rustls-integration.sh
Fix rustls integ test.
* I'm not sure why but for the latest release of rustls-webpki, piping the output of cargo-download into a file was creating an invalid gzip file.
* Changed to using `-o` to specify the file to download the crate into. 
=> Fix rustls integ tests

aws-lc-rs/src/agreement.rs, aws-lc-rs/src/bn.rs, aws-lc-rs/src/cipher.rs, aws-lc-rs/src/digest.rs, aws-lc-rs/src/ec.rs, aws-lc-rs/src/ec/encoding.rs, aws-lc-rs/src/ec/key_pair.rs, aws-lc-rs/src/ec/signature.rs, aws-lc-rs/src/ed25519.rs, aws-lc-rs/src/evp_pkey.rs, aws-lc-rs/src/kem.rs, aws-lc-rs/src/pqdsa.rs, aws-lc-rs/src/pqdsa/key_pair.rs, aws-lc-rs/src/pqdsa/signature.rs, aws-lc-rs/src/ptr.rs, aws-lc-rs/src/rsa/encoding.rs, aws-lc-rs/src/rsa/encryption.rs, aws-lc-rs/src/rsa/key.rs, aws-lc-rs/src/rsa/signature.rs
* Use lifetimes to prevent a "child" object being used after its "parent" is out of scope.
* Move most non-mutating functionality from `LcPtr<EVP_PKEY>` to `ConstPointer<'_, EVP_PKEY>`
=> Ensure ConstPointers don't outlive parent

.github/workflows/integration.yml, scripts/ci/check_sys_crate_compatibility.sh
* When the version numbers of the sys crates change in the repo, but haven't been published yet, the publish dryrun for aws-lc-rs fails.
Output of version check ...
* .. when aws-lc-rs publish dry run should run: https://github.com/aws/aws-lc-rs/actions/runs/16226338787/job/45819025565?pr=840#step:3:35
* .. when aws-lc-rs publish dry run should be skipped: https://github.com/aws/aws-lc-rs/actions/runs/16226343352/job/45819038707?pr=841#step:3:35
* See skipped job: https://github.com/aws/aws-lc-rs/actions/runs/16226343352/job/45819051799?pr=841 
* Tested on this PR: https://github.com/aws/aws-lc-rs/pull/841
=> Skip aws-lc-rs "publish dryrun" job when -sys crates not published

aws-lc-rs/src/aead/rand_nonce.rs
Addresses #842
* Adds support for `AES_128_GCM_SIV` and `AES_256_GCM_SIV` to `RandomizedNonceKey`.
Updated tests to cover new algorithms.
=> Support SIV in RandomizedNonceKey

aws-lc-rs/src/agreement.rs, aws-lc-rs/src/evp_pkey.rs
We previously had two nearly identical methods for performing agreement.  This change consolidates them into an `agree` function in `LcPtr<EVP_PKEY>`
No changes to tests.
=> Consolidate agreement functions into LcPtr<EVP_PKEY>

Cargo.toml, aws-lc-fips-sys/Cargo.toml, aws-lc-sys/Cargo.toml
Fix failing MSRV CI job.
* Latest version of [libloading bumps MSRV to 1.71.0](https://crates.io/crates/libloading/versions).
=> Fix MSRV CI - libloading

aws-lc-rs/src/cipher.rs, aws-lc-rs/tests/cipher_test.rs
See SIM P307101963
Currently, only the PaddedBlock keys and Streaming keys supports CBC mode.
This adds CBC mode for EncryptingKey and DecryptingKey. This allows AES CBC encryption/decryption with no padding.
Since no padding is used, input data must be block aligned, length of input must be a multiple of 16 bytes.
I also included the `DANGER` message in the doc string, since I think the use of this is unconventional.
Unit tests added following examples of existing unit tests.
Added known-answer tests from "Appendix F" of SP800-38a:
* https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf
=> Adds AES CBC mode no padding
